In [20]:
import numpy as np

r = np.array([[1],[2]])
s = np.array([[1,3]])
t = r * s

#print t
#print t * t

u = np.array([[1],[2],[3],[4]])
v = np.array([[2, 3]])
#print u * v

listofarrays = []
listofarrays.append(r)
listofarrays.append(s)
listofarrays.append(t)
print listofarrays

for l in range(0,5):
    print l
print 'xxxxxxxxxx'
for l in range(5,1,-1):
    print l
    
print np.multiply([[1,2]], [[2,3]])

print np.random.random((3,4))

[array([[1],
       [2]]), array([[1, 3]]), array([[1, 3],
       [2, 6]])]
0
1
2
3
4
xxxxxxxxxx
5
4
3
2
[[2 6]]
[[ 0.4173  0.5587  0.1404  0.1981]
 [ 0.8007  0.9683  0.3134  0.6923]
 [ 0.8764  0.8946  0.085   0.0391]]


In [21]:
import numpy as np
r = np.array([[-1],[2]])
s = np.array([[1,3]])
print r.dot(s)
print r*s
r[r < 0] = 0
print r

[[-1 -3]
 [ 2  6]]
[[-1 -3]
 [ 2  6]]
[[0]
 [2]]


In [60]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in xrange(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
print l2

[[ 0.00231155]
 [ 0.99695301]
 [ 0.99631803]
 [ 0.00404382]]


In [2]:
import numpy as np

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    if(abs(x).any>10):
        return np.sign(x)
    return 1/(1+np.exp(-x))

wij = np.array([[0.2,0.1],
             [0.1,0.3]])
                
y = np.array([[0.6]])

aj = np.array([[2], [1]])

wi = np.array([[1], [1]])

xi = wij * aj
x = wi * nonlin(xi, False)

E = 1/2 * (nonlin(x, False) - y)**2

print xi
print x

dEdw = (nonlin(x, False) - y)*nonlin(x, True)*wi*nonlin(xi, True)*aj

print E

alpha = 1

dwij = -alpha * dEdw

print dwij

[[ 0.4  0.2]
 [ 0.1  0.3]]
[[ 0.59868766  0.549834  ]
 [ 0.52497919  0.57444252]]
[[ 0.  0.]
 [ 0.  0.]]
[[-0.00523069 -0.00270067]
 [-0.00063542 -0.00204255]]


In [1]:
import numpy as np

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak inj = sum over k Wkj ak

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

alpha = 1
yi = np.array([[0.6], [0.2]])
ai = np.array([[0.3], [0.2]])
aj = np.array([[0.3], [-0.2]])
wji = np.array([[0.2,0.1],
             [0.1,0.3]]) 
ini = wji * aj
print wji + alpha * (yi-ai) * sigmoid(ini,True) * aj
ak = np.array([[0.4], [-0.1]])
wkj = np.array([[0.1,-0.1],
             [0.1,0.2]]) 
inj = wkj * ak
print wkj + alpha * (yi-ai) * wji * sigmoid(inj,True) * ak

yi = np.array([[0.5], [0.1]])
ai = np.array([[0.3], [0.2]])
aj = np.array([[0.3], [-0.2]]) 
ini = wji * aj
print wji + alpha * (yi-ai) * sigmoid(ini,True) * aj
ak = np.array([[0.4], [-0.1]]) 
inj = wkj * ak
print wkj + alpha * (yi-ai) * wji * sigmoid(inj,True) * ak

yi = np.array([[0.5], [0.1]])
ai = np.array([[0.3], [0.2]])
aj = np.array([[0.3], [-0.2]]) 
ini = wji * aj
print wji + alpha * (yi-ai) * sigmoid(ini,True) * aj
ak = np.array([[0.4], [-0.1]]) 
inj = wkj * ak
print wkj + alpha * (yi-ai) * wji * sigmoid(inj,True) * ak

yi = np.array([[0.5], [0.1]])
ai = np.array([[0.3], [0.2]])
aj = np.array([[0.3], [-0.2]]) 
ini = wji * aj
print wji + alpha * (-yi * np.log(ai)) * sigmoid(ini,True) * aj
ak = np.array([[0.4], [-0.1]]) 
inj = wkj * ak
print wkj + alpha * (-yi * np.log(ai)) * wji * sigmoid(inj,True) * ak

[[ 0.205076  0.102619]
 [ 0.1       0.3     ]]
[[ 0.1009216 -0.1004992]
 [ 0.1        0.2      ]]
[[ 0.203384  0.101746]
 [ 0.099592  0.298728]]
[[ 0.1006144 -0.1003328]
 [ 0.0999899  0.1999388]]
[[ 0.203384  0.101746]
 [ 0.099592  0.298728]]
[[ 0.1006144 -0.1003328]
 [ 0.0999899  0.1999388]]
[[ 0.21018561  0.10525534]
 [ 0.10065665  0.30204721]]
[[ 0.1018493  -0.10100171]
 [ 0.10001626  0.2000985 ]]


In [23]:
import numpy as np

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak inj = sum over k Wkj ak

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

alpha = -0.5
# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1,1]]) # solid = 1111 : last element for bias always 1
vert0 = np.array([[1,0,1,0,1]]) # vertical = 1010
vert1 = np.array([[0,1,0,1,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0,1]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0,1]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = np.array([[-0.2,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1]])
wkj = np.array([[0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1],
                [-0.1,-0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1],
                [-0.2,0.1,-0.2,0.1]]) # bias trick: last line

np.set_printoptions(precision=3)

for i in xrange(10):
    ak = solid
    yi = tsol
    wkj[4] = np.random.rand(4) - np.random.rand(4) # set bias
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

# see if its working: predicted class correct?
ak = solid
inj = np.dot(ak,wkj)
aj = sigmoid(inj,False)
ini = np.dot(aj,wji)
ai = sigmoid(ini,False)
print ai

[[ 0.5  0.5  0.5  0.5]]


In [2]:
a = np.array([[0], [1]])
b = np.array([[0,1], [2,3]])
x1 = a.T.dot(b)
print x1
c = np.array([[1], [2]])
d = np.array([[2,2], [3,2]])
x2 = c.T.dot(d)

print np.dot(b,d)

print b * d

print b
b[1, :] = 3 # Assing to second row
print b
b[:, 1] = 4 # Assing to second column
print b

#[0] #means line 0 of your matrix
#[(0,0)] #means cell at 0,0 of your matrix
#[0:1] #means lines 0 to 1 excluded of your matrix
#[:1] #excluding the first value means all lines until line 1 excluded
#[1:] #excluding the last param mean all lines starting form line 1 included
#[:] #excluding both means all lines
#[::2] #the addition of a second ':' is the sampling. (1 item every 2)
#[::] #exluding it means a sampling of 1
#[:,:] #simply uses a tuple (a single , represents an empty tuple) instead of an index.

[[2 3]]
[[ 3  2]
 [13 10]]
[[0 2]
 [6 6]]
[[0 1]
 [2 3]]
[[0 1]
 [3 3]]
[[0 4]
 [3 4]]


In [27]:
import numpy as np

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj      ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak      inj = sum over k Wkj ak

np.set_printoptions(precision=4)

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

alpha = -0.8
# solid = 11, vertical = 10 or 01, horizontal = 11
solid = np.array([[1,1]]) # solid = 11
half0 = np.array([[1,0]]) # 50% = 10
half1 = np.array([[0,1]]) # 50% = 01
empty = np.array([[0,0]]) # empty = 00

# target outputs
tsol = np.array([[1,0]]) # solid
thal = np.array([[0,1]]) # half
tempt = np.array([[0,0]]) # empty

wji = np.array([[0.1,0.1],
                [0.1,0.1]])
wkj = np.array([[0.1,0.1],
                [0.1,0.1]])

ak = half0
yi = thal
for i in xrange(20):
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

#print wji
#print wkj

# test - see if its working: predicted class correct?
ak = half0
inj = np.dot(ak,wkj)
aj = sigmoid(inj,False)
ini = np.dot(aj,wji)
ai = sigmoid(ini,False)
print ai

[[ 0.7311  0.5   ]]


In [28]:
import numpy as np

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak inj = sum over k Wkj ak

np.set_printoptions(precision=3)

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

alpha = -0.8
# example 20.15 from Russel/Norvig: 6 examples, 14 inputs, 14 outputs 
I1 = np.array([[1,1,1,1,1,1,1,0,0,0,0,0,0,0]])
I2 = np.array([[0,0,0,1,1,0,0,1,1,0,1,0,1,1]])
I3 = np.array([[1,1,1,0,1,0,0,1,1,0,0,0,1,1]])
I4 = np.array([[0,1,0,0,1,0,0,1,0,1,1,1,0,1]])
I5 = np.array([[0,0,1,1,0,1,1,0,1,1,0,0,1,0]])
I6 = np.array([[0,0,0,1,0,1,0,1,1,0,1,1,1,0]])

tout = np.array([[1,1,1,1,1,1,0,1,0,0,0,0,0,0]])

wji = np.array([[0.2,-0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]])
wkj = np.array([[0.2,-0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]])

yi=tout

for i in xrange(1):
    ak = I1 # input
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

for i in xrange(1):
    ak = I2 # input
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

for i in xrange(1):
    ak = I3 # input
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

for i in xrange(1):
    ak = I4 # input
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

for i in xrange(1):
    ak = I5 # input
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

for i in xrange(1):
    ak = I6 # input
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

#print wji
#print wkj

# test - see if its working: predicted class correct?
ak = tout # input
inj = np.dot(ak,wkj)
aj = sigmoid(inj,False)
ini = np.dot(aj,wji)
ai = sigmoid(ini,False)
print yi
print ai

[[1 1 1 1 1 1 0 1 0 0 0 0 0 0]]
[[  9.995e-01   9.997e-01   9.994e-01   9.994e-01   9.994e-01   9.994e-01
    1.860e-04   9.994e-01   1.860e-04   1.860e-04   1.860e-04   1.860e-04
    1.860e-04   1.860e-04]]


In [29]:
import numpy as np
from math import exp

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj      ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak      inj = sum over k Wkj ak

np.set_printoptions(precision=4)

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def sig(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+exp(-x))

alpha = -0.8
# solid = 11, vertical = 10 or 01, horizontal = 11
solid = np.array([[1,1]]) # solid = 11
half0 = np.array([[1,0]]) # 50% = 10
half1 = np.array([[0,1]]) # 50% = 01
empty = np.array([[0,0]]) # empty = 00

# target outputs
tsol = np.array([[1,0]]) # solid
thal = np.array([[0,1]]) # half
tempt = np.array([[0,0]]) # empty

#wji = np.array([[0.1,0.1],
#                [0.1,0.1]])
#wkj = np.array([[0.1,0.1],
#                [0.1,0.1]])

wji00 = 0.1
wji10 = 0.1
wji01 = 0.1
wji11 = 0.1

wkj00 = 0.1
wkj10 = 0.1
wkj01 = 0.1
wkj11 = 0.1

for i in xrange(20):
    ak0 = 1
    ak1 = 1
    yi0 = 1
    yi1 = 0
    #inj = np.dot(ak,wkj)
    inj0 = ak0 * wkj00 + ak1 * wkj10
    inj1 = ak0 * wkj01 + ak1 * wkj11
    #aj = sigmoid(inj,False)
    aj0 = sig(inj0,False)
    aj1 = sig(inj1,False)
    #ini = np.dot(aj,wji)
    ini0 = aj0 * wji00 + aj1 * wji10
    ini1 = aj0 * wji01 + aj1 * wji11
    #ai = sigmoid(ini,False)
    ai0 = sig(ini0,False)
    ai1 = sig(ini1,False)
    #deltai = (yi-ai)
    deltai0 = (yi0-ai0)
    deltai1 = (yi1-ai1)
    # Wji += alpha aj (yi-ai)g'(ini)
    wji00 += alpha * aj0 * deltai0 * sig(ini0,True)
    wji10 += alpha * aj1 * deltai0 * sig(ini0,True)
    wji01 += alpha * aj0 * deltai1 * sig(ini1,True)
    wji11 += alpha * aj1 * deltai1 * sig(ini1,True)
    # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)
    wkj00 += alpha * ak0 * sig(inj0,True) * (wji00 * deltai0 + wji01 * deltai1) 
    wkj10 += alpha * ak1 * sig(inj0,True) * (wji00 * deltai0 + wji01 * deltai1)
    wkj01 += alpha * ak0 * sig(inj1,True) * (wji10 * deltai0 + wji11 * deltai1)
    wkj11 += alpha * ak1 * sig(inj1,True) * (wji10 * deltai0 + wji11 * deltai1)    
    #print wji
    #print wkj

#print wji
#print wkj

# test - see if its working: predicted class correct?
ak0 = 1
ak1 = 1
#inj = np.dot(ak,wkj)
inj0 = ak0 * wkj00 + ak1 * wkj10
inj1 = ak0 * wkj01 + ak1 * wkj11
#aj = sigmoid(inj,False)
aj0 = sig(inj0,False)
aj1 = sig(inj1,False)
#ini = np.dot(aj,wji)
ini0 = aj0 * wji00 + aj1 * wji10
ini1 = aj0 * wji01 + aj1 * wji11
#ai = sigmoid(ini,False)
ai0 = sig(ini0,False)
ai1 = sig(ini1,False)
print ai0
print ai1

0.500007326623
0.731059387618


In [30]:
# pattern recognition deep neural network
# 1 input layer, 3 hidden layer, 1 output layer
# am - wml - al - wlk - ak - wkj - aj - wji - ai : yi target output
# ---------sig---------sig--------sig--------rect----
# 4---------4-----------4----------8----------4------
import numpy as np
np.set_printoptions(precision=4)

def sigmoid(x,deriv=False): # sigmoid
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def rect(x,deriv=False): # rectifier, might use smooth version f(x)=ln(1+exp(x)), f'=exp(x)/(1+exp(x))
    if(deriv==True):
        x[x > 0] = 1
    x[x < 0] = 0
    return x

alpha = -0.8
# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1]]) # solid = 1111
vert0 = np.array([[1,0,1,0]]) # vertical = 1010
vert1 = np.array([[0,1,0,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = np.array([[-0.2,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1]])
wkj = np.array([[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1,0.1,0.1,0.1,0.1],
                [-0.1,-0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1,0.1,0.1,0.1,0.1]])
wlk = np.array([[0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1],
                [-0.1,-0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1]])
wml = np.array([[0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1],
                [-0.1,-0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1]])

# training
for i in xrange(10):
    am = solid # input
    yi = tsol # target output
    inl = np.dot(am,wml)
    al = sigmoid(inl,False)
    ink = np.dot(al,wlk)
    ak = sigmoid(ink,False)
    inj = np.dot(ak,wkj)
    aj = rect(inj,False)
    ai = np.dot(aj,wji)
    deltai = alpha * (yi-ai)
    wji += deltai * aj.T
    #wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T)))
    wkj += (deltai * wji * sigmoid(inj,True).T * ak).T
    #wlk += alpha * np.dot(al.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T)))
    #print np.dot(sigmoid(ink,True), wkj)
    #print deltai * wji * sigmoid(inj,True).T
    #print np.dot(np.dot(sigmoid(ink,True), wkj),(deltai * wji * sigmoid(inj,True).T)) * al.T
    wlk += np.dot(np.dot(sigmoid(ink,True), wkj),(deltai * wji * sigmoid(inj,True).T)) * al.T
    #print np.dot(sigmoid(inl,True), wlk)
    #print wkj * sigmoid(ink,True).T
    #print deltai * wji * sigmoid(inj,True).T
    #print np.dot((deltai * wji * sigmoid(inj,True).T).T,(wkj * sigmoid(ink,True).T).T)
    #print np.dot((deltai * wji * sigmoid(inj,True).T).T,(wkj * sigmoid(ink,True).T).T) * am.T
    wml += np.dot((deltai * wji * sigmoid(inj,True).T).T,(wkj * sigmoid(ink,True).T).T) * am.T

# test
am = solid # input
inl = np.dot(am,wml)
al = sigmoid(inl,False)
ink = np.dot(al,wlk)
ak = sigmoid(ink,False)
inj = np.dot(ak,wkj)
aj = rect(inj,False)
ai = np.dot(aj,wji)
print ai

[[ -2.3686e-15   4.8034e-16   1.8790e-16   4.8034e-16]]


In [31]:
# pattern recognition deep neural network
# 1 input layer, 3 hidden layer, 1 output layer
# am - wml - al - wlk - ak - wkj - aj - wji - ai : yi target output
# ---------sig---------sig--------sig--------rect----
# 4---------4-----------4----------8----------4------
import numpy as np
np.set_printoptions(precision=4)

def sigmoid(x,deriv=False): # sigmoid
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def rect(x,deriv=False): # rectifier, might use smooth version f(x)=ln(1+exp(x)), f'=exp(x)/(1+exp(x))
    if(deriv==True):
        x[x > 0] = 1
    x[x < 0] = 0
    return x

alpha = -0.8
# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1]]) # solid = 1111
vert0 = np.array([[1,0,1,0]]) # vertical = 1010
vert1 = np.array([[0,1,0,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = np.array([[-0.2,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,-0.1,0.1],
                [-0.1,0.1,0.1,0.1],
                [0.1,0.1,0.1,0.1]])
wkj = np.array([[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1,0.1,0.1,0.1,0.1],
                [-0.1,-0.1,0.1,0.1,0.1,0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1,0.1,0.1,0.1,0.1]])
wlk = np.array([[0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1],
                [-0.1,-0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1]])
wml = np.array([[0.1,0.1,0.1,0.1],
                [0.1,0.2,-0.1,-0.1],
                [-0.1,-0.1,0.1,0.1],
                [0.2,0.1,0.2,0.1]])

# training
for i in xrange(5):
    am = solid # input
    yi = tsol # target output
    inl = np.dot(am,wml)
    al = sigmoid(inl,False)
    ink = np.dot(al,wlk)
    ak = sigmoid(ink,False)
    inj = np.dot(ak,wkj)
    aj = rect(inj,False)
    ai = np.dot(aj,wji)
    deltai = alpha * (yi-ai)
    wji += deltai * aj.T
    wkj += (deltai * wji * sigmoid(inj,True).T * ak).T
    wlk += np.dot(np.dot(sigmoid(ink,True), wkj),(deltai * wji * sigmoid(inj,True).T)) * al.T
    wml += np.dot((deltai * wji * sigmoid(inj,True).T).T,(wkj * sigmoid(ink,True).T).T) * am.T

    am = vert0 # input
    yi = tvert # target output
    inl = np.dot(am,wml)
    al = sigmoid(inl,False)
    ink = np.dot(al,wlk)
    ak = sigmoid(ink,False)
    inj = np.dot(ak,wkj)
    aj = rect(inj,False)
    ai = np.dot(aj,wji)
    deltai = alpha * (yi-ai)
    wji += deltai * aj.T
    wkj += (deltai * wji * sigmoid(inj,True).T * ak).T
    wlk += np.dot(np.dot(sigmoid(ink,True), wkj),(deltai * wji * sigmoid(inj,True).T)) * al.T
    wml += np.dot((deltai * wji * sigmoid(inj,True).T).T,(wkj * sigmoid(ink,True).T).T) * am.T
    
    am = diag0 # input
    yi = tdiag # target output
    inl = np.dot(am,wml)
    al = sigmoid(inl,False)
    ink = np.dot(al,wlk)
    ak = sigmoid(ink,False)
    inj = np.dot(ak,wkj)
    aj = rect(inj,False)
    ai = np.dot(aj,wji)
    deltai = alpha * (yi-ai)
    wji += deltai * aj.T
    wkj += (deltai * wji * sigmoid(inj,True).T * ak).T
    wlk += np.dot(np.dot(sigmoid(ink,True), wkj),(deltai * wji * sigmoid(inj,True).T)) * al.T
    wml += np.dot((deltai * wji * sigmoid(inj,True).T).T,(wkj * sigmoid(ink,True).T).T) * am.T

# test
am = vert0 # input
inl = np.dot(am,wml)
al = sigmoid(inl,False)
ink = np.dot(al,wlk)
ak = sigmoid(ink,False)
inj = np.dot(ak,wkj)
aj = rect(inj,False)
ai = np.dot(aj,wji)
print ai

[[ 0.  0.  0.  0.]]


In [32]:
# pattern recognition deep neural network
# 1 input layer, 3 hidden layer, 1 output layer
# am - wml - al - wlk - ak - wkj - aj - wji - ai : yi target output
# ---------sig---------sig--------sig--------rect----
# 4---------4-----------4----------8----------4------

# repeat
#   for each e in examples
#      for each node j in input layer (l=0): aj = xj
#      for l=1 to L-1:
#        ini = sum j: wji aj
#        ai = g(ini)
#      for each node i in output layer (l=L-1)
#        deltai = g'(ini) (yi(e)-ai)
#      for l=L-2 to 0:
#        for each node j in layer l:
#          deltaj = g'(inj) sum i: wji deltai
#          for each node i in layer l+1:
#            wji += alpha aj deltai
# until stopping criterion reached

import numpy as np
np.set_printoptions(precision=4)

def sigmoid(x,deriv=False): # sigmoid
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def rect(x,deriv=False): # rectifier, might use smooth version f(x)=ln(1+exp(x)), f'=exp(x)/(1+exp(x))
    if(deriv==True):
        x[x > 0] = 1
    x[x < 0] = 0
    return x

L = 5 # number of layers
imax = 100
alpha = -1

def gfunc(x,l,deriv=False): # response function by layer
    if l == L-1:
        x = rect(ini[l],False)
    else:
        x = sigmoid(ini[l],False)
    return x   

# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1]]) # solid = 1111
vert0 = np.array([[1,0,1,0]]) # vertical = 1010
vert1 = np.array([[0,1,0,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = []
wji.append(0.2*np.random.random((4,4))-0.05)
wji.append(0.2*np.random.random((4,4))-0.05)
wji.append(0.2*np.random.random((4,8))-0.05)
wji.append(0.2*np.random.random((8,4))-0.05)

ini = []
ai = []
deltai = []

# init ai
ai.append(np.array([[0,0,0,0]])) # 0
ai.append(np.array([[0,0,0,0]])) # 1
ai.append(np.array([[0,0,0,0]])) # 2
ai.append(np.array([[0,0,0,0,0,0,0,0]])) # 3
ai.append(np.array([[0,0,0,0]])) # 4

# init ini
ini.append(np.array([[0,0,0,0]]))
ini.append(np.array([[0,0,0,0]]))
ini.append(np.array([[0,0,0,0]]))
ini.append(np.array([[0,0,0,0,0,0,0,0]]))
ini.append(np.array([[0,0,0,0]]))

# init deltai
deltai.append(np.array([[0,0,0,0]]))
deltai.append(np.array([[0,0,0,0]]))
deltai.append(np.array([[0,0,0,0]]))
deltai.append(np.array([[0,0,0,0,0,0,0,0]]))
deltai.append(np.array([[0,0,0,0]]))

for i in range(imax):
    ai[0] = solid # input
    yi = tsol #target output     
    for l in range(1, L):
        ini[l] = np.dot(ai[l-1],wji[l-1])
        ai[l] = gfunc(ini[l],l,False)
    deltai[L-1] = np.multiply(gfunc(ini[L-1],L-1,True),(ai[L-1] - yi)) # component-wise multiply
    #print("error %s  " % ((yi - ai[L-1])))
    for l in range(L-2, -1, -1):
        deltai[l] = np.multiply(gfunc(ini[l],l,True), np.dot(wji[l], deltai[l+1].T).T)
        wji[l] += alpha * np.multiply(ai[l].T, deltai[l+1])

ai[0] = hor1 # input
for l in range(1, L):
    ini[l] = np.dot(ai[l-1],wji[l-1])
    ai[l] = gfunc(ini[l],l,False)
print str(ai[L-1])

[[ 1.021   0.0046  0.0046  0.0046]]


In [33]:
# pattern recognition deep neural network
# 1 input layer, 3 hidden layer, 1 output layer
# am - wml - al - wlk - ak - wkj - aj - wji - ai : yi target output
# ---------sig---------sig--------sig--------rect----
# 4---------4-----------4----------8----------4------

# repeat
#   for each e in examples
#      for each node j in input layer (l=0): aj = xj
#      for l=1 to L-1:
#        ini = sum j: wji aj
#        ai = g(ini)
#      for each node i in output layer (l=L-1)
#        deltai = g'(ini) (yi(e)-ai)
#      for l=L-2 to 0:
#        for each node j in layer l:
#          deltaj = g'(inj) sum i: wji deltai
#          for each node i in layer l+1:
#            wji += alpha aj deltai
# until stopping criterion reached

import numpy as np
np.set_printoptions(precision=4)

def sigmoid(x,deriv=False): # sigmoid
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def rect(x,deriv=False): # rectifier, might use smooth version f(x)=ln(1+exp(x)), f'=exp(x)/(1+exp(x))
    if(deriv==True):
        x[x > 0] = 1
    x[x < 0] = 0
    return x

L = 5 # number of layers
imax = 3
alpha = 1

def gfunc(x,l,deriv=False): # response function by layer
    if l == L-1:
        x = rect(ini[l],False)
    else:
        x = sigmoid(ini[l],False)
    return x  

def L_i(x, y, W):
  """
  unvectorized version. Compute the multiclass svm loss for a single example (x,y)
  - x is a column vector representing an image (e.g. 3073 x 1 in CIFAR-10)
    with an appended bias dimension in the 3073-rd position (i.e. bias trick)
  - y is an integer giving index of correct class (e.g. between 0 and 9 in CIFAR-10)
  - W is the weight matrix (e.g. 10 x 3073 in CIFAR-10)
  """
  delta = 1.0 # see notes about delta later in this section
  scores = W.dot(x) # scores becomes of size 10 x 1, the scores for each class
  correct_class_score = scores[y]
  D = W.shape[0] # number of classes, e.g. 10
  loss_i = 0.0
  for j in xrange(D): # iterate over all wrong classes
    if j == y:
      # skip for the true class to only loop over incorrect classes
      continue
    # accumulate loss for the i-th example
    loss_i += max(0, scores[j] - correct_class_score + delta)
  return loss_i

def L_i_vectorized(x, y, W):
  """
  A faster half-vectorized implementation. half-vectorized
  refers to the fact that for a single example the implementation contains
  no for loops, but there is still one loop over the examples (outside this function)
  """
  delta = 1.0
  scores = W.dot(x)
  # compute the margins for all classes in one vector operation
  margins = np.maximum(0, scores - scores[y] + delta)
  # on y-th position scores[y] - scores[y] canceled and gave delta. We want
  # to ignore the y-th position and only consider margin on max wrong class
  margins[y] = 0
  loss_i = np.sum(margins)
  return loss_i

def L_i_fullvec(X, y, W):
  """
  fully-vectorized implementation :
  - X holds all the training examples as columns (e.g. 3073 x 50,000 in CIFAR-10)
  - y is array of integers specifying correct class (e.g. 50,000-D array)
  - W are weights (e.g. 10 x 3073)
  """
  # evaluate loss over all examples in X without using any for loops
  # left as exercise to reader in the assignment

def softmax(y, a):
    return -np.log(np.exp(y) / np.sum(np.exp(a)))

def totloss(y, a, w):
    reg = 0.001
    data_loss = np.sum(softmax(y, a))/len(y)
    reg_loss = 0.5*reg*np.sum(w*w)
    loss = data_loss + reg_loss
    return loss

def dscore(y, a):
    return ((np.exp(y) / np.sum(np.exp(a)))-1) / len(y)

# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1]]) # solid = 1111
vert0 = np.array([[1,0,1,0]]) # vertical = 1010
vert1 = np.array([[0,1,0,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = []
wji.append(0.2*np.random.random((4,5))-0.05) # bias on 2nd axis
wji.append(0.2*np.random.random((5,5))-0.05) # bias on 1st+2nd axis
wji.append(0.2*np.random.random((5,9))-0.05) # bias on 1st+2nd axis
wji.append(0.2*np.random.random((9,4))-0.05) # bias on 1st axis
# bias should be init to 0
wji[0][:,4] = 0 # b[1,:]...2nd row, b[:,1]...2nd column
wji[1][:,4] = 0
wji[1][4,:] = 0
wji[2][:,8] = 0
wji[2][4,:] = 0
wji[3][4,:] = 0

ini = []
ai = []
deltai = []

# init ai
ai.append(np.array([[0,0,0,0]])) # 0
ai.append(np.array([[0,0,0,0,0]])) # 1 + bias
ai.append(np.array([[0,0,0,0,0]])) # 2 + bias
ai.append(np.array([[0,0,0,0,0,0,0,0,0]])) # 3 + bias
ai.append(np.array([[0,0,0,0]])) # 4

# init ini
ini.append(np.array([[0,0,0,0]]))
ini.append(np.array([[0,0,0,0,0]]))
ini.append(np.array([[0,0,0,0,0]]))
ini.append(np.array([[0,0,0,0,0,0,0,0,0]]))
ini.append(np.array([[0,0,0,0]]))

# init deltai
deltai.append(np.array([[0,0,0,0]]))
deltai.append(np.array([[0,0,0,0,0]]))
deltai.append(np.array([[0,0,0,0,0]]))
deltai.append(np.array([[0,0,0,0,0,0,0,0,0]]))
deltai.append(np.array([[0,0,0,0]]))

for i in range(imax):
    ai[0] = vert0 # input
    yi = tvert #target output     
    for l in range(1, L):
        ini[l] = np.dot(ai[l-1],wji[l-1])
        ai[l] = gfunc(ini[l],l,False)
    #deltai[L-1] = np.multiply(gfunc(ini[L-1],L-1,True),(ai[L-1] - yi)) # component-wise multiply
    deltai[L-1] = np.multiply(gfunc(ini[L-1],L-1,True),dscore(yi, ai[L-1]))
    #print dscore(yi, ai[L-1])
    for l in range(L-2, -1, -1):
        deltai[l] = np.multiply(gfunc(ini[l],l,True), np.dot(wji[l], deltai[l+1].T).T)
        wji[l] += alpha * np.multiply(ai[l].T, deltai[l+1])
        #print deltai[l]

ai[0] = vert0 # input
for l in range(1, L):
    ini[l] = np.dot(ai[l-1],wji[l-1])
    ai[l] = gfunc(ini[l],l,False)
print str(ai[L-1])

[[ 0.  0.  0.  0.]]


In [2]:
# forward pass
W = np.random.randn(2, 3)
X = np.random.randn(3, 2)
D = W.dot(X)

# now suppose we had the gradient on D from above in the circuit
dD = np.random.randn(*D.shape) # same shape as D
dW = dD.dot(X.T) #.T gives the transpose of the matrix
dX = W.T.dot(dD)

print dX

[[ 4.1245 -0.927 ]
 [-4.1057 -1.7168]
 [-0.5382  2.5761]]


In [3]:
# X = (hours sleeping, hours studying), y = Score on test
X = np.array(([3,5], [5,1], [10,2]), dtype=float)
y = np.array(([75], [82], [93]), dtype=float)

In [1]:
import numpy as np

# numerical stability in softmax classifier

f = np.array([123, 456, 789])
p = np.exp(f) / np.sum(np.exp(f))

print p

f -= np.max(f)
p = np.exp(f) / np.sum(np.exp(f))

print p

[  0.   0.  nan]
[  5.75274406e-290   2.39848787e-145   1.00000000e+000]


D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: overflow encountered in exp
D:\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: RuntimeWarning: invalid value encountered in divide


In [9]:
# SVM vs softmax
w = np.array([[0.01, -0.05, 0.1, 0.05], [0.7, 0.2, 0.05, 0.16], [0.0, -0.45, -0.2, 0.03]])
xi = np.array([[-15], [22], [-44], [56]])
b = np.array([[0.0], [0.2], [-0.3]])
yi = 2

f = np.dot(w,xi)+b
print f
print np.exp(f)
print np.exp(f) / np.sum(np.exp(f))
print -np.log(np.exp(f) / np.sum(np.exp(f)))

[[-2.85]
 [ 0.86]
 [ 0.28]]
[[ 0.05784432]
 [ 2.36316069]
 [ 1.32312981]]
[[ 0.01544932]
 [ 0.63116335]
 [ 0.35338733]]
[[ 4.17019057]
 [ 0.46019057]
 [ 1.04019057]]


In [9]:
import numpy as np

def L(x, y, w):
    delta = 1.0
    scores = x.dot(w)
    margins = np.maximum(0, scores - scores[y] + delta)
    margins[y] = 0
    loss_i = np.sum(margins)
    return loss_i

w = np.random.randn(10, 3073) * 0.001 # random starting w
#xtr_cols = np.array([[-15], [22], [-44], [56], [-15], [22], [-44], [56], [-15], [22]])
xtr_cols = np.array([-15, 22, -44, 56, 15, 22, -44, 56, -15, 22])
xtr_cols = np.transpose(xtr_cols)
ytr = 2
bestloss = float("inf")
for i in xrange(1):
    step_size = 0.0001
    wtr = w + np.random.randn(10, 3073) * step_size
    loss = L(xtr_cols, ytr, wtr)
    if loss < bestloss:
        w = wtr
        bestloss = loss
    print 'iter %d loss is %f' % (i, bestloss)

iter 0 loss is 2854.972995


In [1]:
import numpy as np

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak inj = sum over k Wkj ak

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

alpha = 0.8
# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1,1]]) # solid = 1111 : last element for bias always 1
vert0 = np.array([[1,0,1,0,1]]) # vertical = 1010
vert1 = np.array([[0,1,0,1,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0,1]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0,1]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = np.random.rand(4,4) - np.random.rand(4,4)
wkj = np.random.rand(5,4) - np.random.rand(5,4) # bias trick: last line

np.set_printoptions(precision=3)

for i in xrange(100):
    ak = diag0
    yi = tdiag
    wkj[4] = np.random.rand(4) - np.random.rand(4) # set bias
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

# see if its working: predicted class correct?
ak = diag0
inj = np.dot(ak,wkj)
aj = sigmoid(inj,False)
ini = np.dot(aj,wji)
ai = sigmoid(ini,False)
print [[1,1,1,1]] - ai

[[0.  0.5 1.  0.5]]


In [12]:
import numpy as np

x = np.array([[1,2],[3,4]])
print np.repeat(np.repeat(x, 2, axis=1), 2, axis=0) # doble entries along both axes (0: column, 1: row)
y = np.array([[1,2],[4,5],[7,8]])
z = y.copy() # copy an array
#z[2] = 0
z = np.delete(z, (2), axis=0) # delete last row
print z
newrow = [9,9] # new row
z = np.vstack([z, newrow]) # add new row
print z

[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]
[[1 2]
 [4 5]]
[[1 2]
 [4 5]
 [9 9]]


In [67]:
# NN with iterative split
import numpy as np

# input a_k -- Wkj -- g(in_j) -  hidden a_j -- Wji -- g(in_i) - output a_i - y_i
# hidden to output layer
# Wji = Wji + alpha (yi-ai)g'(ini)aj ini=sum over j Wji aj
# input to hidden layer
# Wkj = Wkj + alpha sum over i (yi-ai) Wji g'(inj) ak inj = sum over k Wkj ak

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

alpha = 0.8
# solid = 1111, vertical = 1010 or 0101, diagonal = 1001 or 0110, horizontal = 1100 or 0011
# bias as last element
solid = np.array([[1,1,1,1,1]]) # solid = 1111 : last element for bias always 1
vert0 = np.array([[1,0,1,0,1]]) # vertical = 1010
vert1 = np.array([[0,1,0,1,1]]) # vertical = 0101
diag0 = np.array([[1,0,0,1,1]]) # diagonal = 1001
diag1 = np.array([[0,1,1,0,1]]) # diagonal = 0110
hor0 = np.array([[1,1,0,0,1]]) # horizontal = 1100
hor1 = np.array([[0,0,1,1,1]]) # horizontal = 0011

# target outputs
tsol = np.array([[1,0,0,0]]) # solid
tvert = np.array([[0,1,0,0]]) # vertical
tdiag = np.array([[0,0,1,0]]) # diagonal
thor = np.array([[0,0,0,1]]) # horizontal

wji = np.random.rand(4,4) - np.random.rand(4,4)
wkj = np.random.rand(5,4) - np.random.rand(5,4) # bias trick: last line

np.set_printoptions(precision=3)

iterctr = 2 # count iterations to keep track of matrix size
# matrices to double: wji, wkj
useiter = False

for i in xrange(100):
    ak = solid
    yi = tdiag
    if i == 50 or i==75 and useiter: # test: double at middle
        # double wkj along axis 1 (rows)
        cwkj = wkj.copy()
        cwkj = np.delete(cwkj, (wkj.shape[0]-1), axis=0) # delete last row
        cwkj = np.repeat(cwkj, 2, axis=1)
        #print cwkj
        biasrow = np.random.rand(cwkj.shape[1]) - np.random.rand(cwkj.shape[1])
        cwkj = np.vstack([cwkj, biasrow]) # add new row
        wkj = cwkj.copy() # copy back
        # double wji along axis 0 (columns)
        wji = np.repeat(wji, 2, axis=0)
        iterctr += 1
    wkj[4] = np.random.rand(wkj.shape[1]) - np.random.rand(wkj.shape[1]) # set bias
    inj = np.dot(ak,wkj)
    aj = sigmoid(inj,False)
    ini = np.dot(aj,wji)
    ai = sigmoid(ini,False)
    deltai = (yi-ai)
    wji += alpha * aj.T * deltai * sigmoid(ini,True) # Wji += alpha (yi-ai)g'(ini)aj 
    wkj += alpha * np.dot(ak.T,np.dot(sigmoid(inj,True),np.dot(wji,deltai.T))) # Wkj += alpha ak g'(inj) sum i Wji(yi-ai)

# see if its working: predicted class correct?
ak = diag0
inj = np.dot(ak,wkj)
aj = sigmoid(inj,False)
ini = np.dot(aj,wji)
ai = sigmoid(ini,False)
print [[1,1,1,1]] - ai

[[0. 0. 1. 0.]]
