In [1]:
import numpy as np

def levenshtein(seq1, seq2):  
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in xrange(size_x):
        matrix [x, 0] = x
    for y in xrange(size_y):
        matrix [0, y] = y

    for x in xrange(1, size_x):
        for y in xrange(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

if __name__=='__main__':
    print levenshtein('test', 'toast')

[[ 0.  1.  2.  3.  4.  5.]
 [ 1.  0.  1.  2.  3.  4.]
 [ 2.  1.  1.  2.  3.  4.]
 [ 3.  2.  2.  2.  2.  3.]
 [ 4.  3.  3.  3.  3.  2.]]
2.0


In [1]:
# Haiku generator
from random import randint

wordList1 = ["berauschend", "erstaunlich", "farbenfroh", "entzückend", "zarteste"]
wordList2 = ["Visionen", "Entfernung", "Gewissen", "Prozess", "Chaos"]
wordList3 = ["abergläubisch", "kontrastierend", "anmutig", "einladend", "widersprüchlich", "überwältigend"]
wordList4 = ["wahrer", "dunkler", "kalter", "warmer", "heller"]
wordList5 = ["Landschaft", "Jahreszeit", "Farben", "Licht", "Frühling", "Winter", "Sommer", "Herbst"]
wordList6 = ["unbestreitbare", "schöne", "unersetzliche", "unglaubliche", "unwiderrufliche"]
wordList7 = ["Inspiration", "Phantasie", "Weisheit", "Gedanken"]

wordIndex1=randint(0, len(wordList1)-1)
wordIndex2=randint(0, len(wordList2)-1)
wordIndex3=randint(0, len(wordList3)-1)
wordIndex4=randint(0, len(wordList4)-1)
wordIndex5=randint(0, len(wordList5)-1)
wordIndex6=randint(0, len(wordList6)-1)
wordIndex7=randint(0, len(wordList7)-1)

haiku = wordList1[wordIndex1] + " " + wordList2[wordIndex2] + ",\n" 
haiku = haiku + wordList3[wordIndex3] + " " + wordList4[wordIndex4] + " " + wordList5[wordIndex5]  + ",\n"
haiku = haiku + wordList6[wordIndex6] + " " + wordList7[wordIndex7] + "."

print(haiku)

entzückend Chaos,
kontrastierend kalter Landschaft,
unersetzliche Phantasie.


In [2]:
zip([1,2,3], ['a', 'b', 'c'], [1,2,3])

[(1, 'a', 1), (2, 'b', 2), (3, 'c', 3)]

In [3]:
# semiprimes
import math

def sieveEra(n):
    alst = [1] * (n+1)
    ilim = int(math.sqrt(n))+1
    for i in range(2, ilim):
        if alst[i] == 1:
            j = i*i
            while j <= n:
                alst[j] = 0
                j += i
    return alst

def primes(n): # returns a list of primes up to n
    alst = sieveEra(n)
    res = []
    for i in range(2,n):
        if alst[i] > 0:
            res.append(i * alst[i])
    return res

def factors(n): # only true factors
    res = []
    lp = primes(int(n/2))
    for p in lp:
        if n % p == 0:
            elim = int(math.log(n)/math.log(p))
            for e in range(1, elim+2):
                if n % (p**e) != 0:
                    res.append((p, e-1))
                    break
    return res

def issemip(n):
    lf = factors(n)
    for e in lf:
        if e[1] > 1:
            return False
    return True

if __name__=='__main__':
    #print sieveEra(10)
    print factors(28)
    print factors(120)
    print factors(108)
    print factors(42)
    print factors(48)
    print factors(180)
    print issemip(46)

[(2, 2), (7, 1)]
[(2, 3), (3, 1), (5, 1)]
[(2, 2), (3, 3)]
[(2, 1), (3, 1), (7, 1)]
[(2, 4), (3, 1)]
[(2, 2), (3, 2), (5, 1)]
True


In [42]:
from __future__ import print_function
 
import sys
from itertools import islice, cycle, count
 
try:
    from itertools import compress
except ImportError:
    def compress(data, selectors):
        """compress('ABCDEF', [1,0,1,0,1,1]) --> A C E F"""
        return (d for d, s in zip(data, selectors) if s)
 
 
def is_prime(n):
    return list(zip((True, False), decompose(n)))[-1][0]
 
class IsPrimeCached(dict):
    def __missing__(self, n):
        r = is_prime(n)
        self[n] = r
        return r
 
is_prime_cached = IsPrimeCached()
 
def croft():
    """Yield prime integers using the Croft Spiral sieve.
 
    This is a variant of wheel factorisation modulo 30.
    """
    # Copied from:
    #   https://code.google.com/p/pyprimes/source/browse/src/pyprimes.py
    # Implementation is based on erat3 from here:
    #   http://stackoverflow.com/q/2211990
    # and this website:
    #   http://www.primesdemystified.com/
    # Memory usage increases roughly linearly with the number of primes seen.
    # dict ``roots`` stores an entry x:p for every prime p.
    for p in (2, 3, 5):
        yield p
    roots = {9: 3, 25: 5}  # Map d**2 -> d.
    primeroots = frozenset((1, 7, 11, 13, 17, 19, 23, 29))
    selectors = (1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0)
    for q in compress(
            # Iterate over prime candidates 7, 9, 11, 13, ...
            islice(count(7), 0, None, 2),
            # Mask out those that can't possibly be prime.
            cycle(selectors)
            ):
        # Using dict membership testing instead of pop gives a
        # 5-10% speedup over the first three million primes.
        if q in roots:
            p = roots[q]
            del roots[q]
            x = q + 2*p
            while x in roots or (x % 30) not in primeroots:
                x += 2*p
            roots[x] = p
        else:
            roots[q*q] = q
            yield q
primes = croft
 
def decompose(n):
    for p in primes():
        if p*p > n: break
        while n % p == 0:
            yield p
            n //=p
    if n > 1:
        yield n
 
 
if __name__ == '__main__':
    # Example: calculate factors of Mersenne numbers to M59 #
 
    import time
 
    for m in primes():
        p = 2 ** m - 1
        print( "2**{0:d}-1 = {1:d}, with factors:".format(m, p) )
        start = time.time()
        for factor in decompose(p):
            print(factor, end=' ')
            sys.stdout.flush()
 
        print( "=> {0:.2f}s".format( time.time()-start ) )
        if m >= 59:
            break

2**2-1 = 3, with factors:
3 => 0.00s
2**3-1 = 7, with factors:
7 => 0.00s
2**5-1 = 31, with factors:
31 => 0.00s
2**7-1 = 127, with factors:
127 => 0.00s
2**11-1 = 2047, with factors:
23 89 => 0.00s
2**13-1 = 8191, with factors:
8191 => 0.00s
2**17-1 = 131071, with factors:
131071 => 0.00s
2**19-1 = 524287, with factors:
524287 => 0.00s
2**23-1 = 8388607, with factors:
47 178481 => 0.01s
2**29-1 = 536870911, with factors:
233 1103 2089 => 0.01s
2**31-1 = 2147483647, with factors:
2147483647 => 0.01s
2**37-1 = 137438953471, with factors:
223 616318177 => 0.01s
2**41-1 = 2199023255551, with factors:
13367 164511353 => 0.01s
2**43-1 = 8796093022207, with factors:
431 9719 2099863 => 0.01s
2**47-1 = 140737488355327, with factors:
2351 4513 13264529 => 0.01s
2**53-1 = 9007199254740991, with factors:
6361 69431 20394401 => 0.02s
2**59-1 = 576460752303423487, with factors:
179951 3203431780337 => 0.39s


In [1]:
# exploding dots

def resolve(n, nlim, nexp, nlft):
    res = [n]
    i = 0
    while True:
        while res[i] >= nlim:
            res[i] -= (nexp + nlft)
            if i == len(res)-1:
                res.append(nlft)
            else:
                res[i+1] += nlft
        i += 1
        if res[i] < nlim:
            break
    return res

if __name__=='__main__':
    print resolve(8, 3, 1, 2)
    print resolve(19, 4, 1, 3)

[2, 1, 2]
[3, 0, 1, 2, 3]


In [3]:
import pygame.midi
import time

pygame.midi.init()
player = pygame.midi.Output(0)
player.set_instrument(0)
player.note_on(64, 127) # 74 is the midi note number https://newt.phys.unsw.edu.au/jw/notes.html
time.sleep(1)
player.note_off(64, 127)
del player
pygame.midi.quit()

In [4]:
# tune test
import pygame.midi
import time

def playnote(pl, n, lgth):
    pl.note_on(n, 127) # midi note number https://newt.phys.unsw.edu.au/jw/notes.html and loudness
    time.sleep(lgth)
    pl.note_off(n, 127)
    return 0

if __name__=='__main__':
    pygame.midi.init()
    pl = pygame.midi.Output(0)
    pl.set_instrument(0)
    tunen = [45, 64, 64, 45, 57, 33]
    tunel = [0.8, 0.5, 0.5, 0.8, 0.6, 1]
    for i in range(len(tunen)):
        playnote(pl, tunen[i], tunel[i])
    del pl
    pygame.midi.quit()

In [1]:
# binom sums
import math

def binom(a,b):
    if a==0 or a <= b:
        return 1
    return math.factorial(a) / math.factorial(b) / math.factorial(a-b)

def aa(n):
    res = 0
    for k in range(0,n+1,2):
        res += binom(n, k)
    return res

def bb(n):
    res = 0
    for k in range(1,n+1,2):
        res += binom(n, k)
    return res

def bb2(n):
    res = 0
    for k in range(0,n+1,2):
        res += binom(n, k) * (n+1) / (k+1)
    return res/2

if __name__=='__main__':
    n = 14
    print aa(n)
    print bb(n)
    print bb2(n)

8192
8192
8192


In [8]:
from gensim.corpora import Dictionary

texts = [['human', 'interface', 'computer']]
dct = Dictionary(texts)  # initialize a Dictionary
dct.add_documents([["cat", "say", "meow"], ["dog"]])  # add more document (extend the vocabulary)
# Convert document into the bag-of-words (BoW) format = list of (token_id, token_count) tuples
dct.doc2bow(["dog", "computer", "non_existent_word"], return_missing=True)
dct[2] # dct.id2token(2)
print dct

Dictionary(7 unique tokens: [u'meow', u'dog', u'cat', u'say', u'computer']...)


In [5]:
# integer equations

def e1(x,y,z):
    return x*y+x*z-357

def e2(x,y,z):
    return x*y+y*z-37

if __name__=='__main__':
    for x in range(1,60):
        for y in range(1,60):
            for z in range(1,60):
                if e1(x,y,z) == 0 and e2(x,y,z) == 0:
                    print '%d %d %d' %  (x,y,z)
                    print x*y*z

17 1 20
340
21 1 16
336


In [66]:
# Googol
import random

def genslips(n):
    res = []
    for i in range(n):
        res.append(random.uniform(0.00001, 100000000.))
    return res

def choosen(n, slips):
    ms = max(slips)
    ns = len(slips)
    for k in range(n):
        if slips[random.randrange(ns)] >= ms:
            return True
    return False

def strat0(slips):
    ms = max(slips)
    avchoice = 0.
    for k in range(len(slips)-1):
        thischoice = slips.pop(random.randrange(len(slips)))
        if k > 0:
            if thischoice > avchoice:
                if thischoice == ms:
                    return (k, True)
                else:
                    return (k, False)
        avchoice += thischoice/(k+1.)
    return (len(slips)-1, False)

def rej(n, p):
    res = 0.
    for k in range(p,n-1):
        res += 1./k
    return res * p / n

def nrej(n):
    lastp = 0.
    for k in range(2,n):
        thisp = rej(n,k)
        if thisp < lastp:
            return k
        lastp = thisp
    return n

if __name__=='__main__':
    n = 10
    ns = genslips(n)
    res = [0] * n
    nruns = 1000
    nsucc = 0
    for i in range(nruns):
        #for k in range(1,n):
            #if choosen(k, ns):
                #res[k] += 1
        ns = genslips(n)
        if strat0(ns)[1]:
            nsucc += 1
    #print res
    print float(nsucc) / nruns
    print nrej(n)

0.182
4


In [1]:
# Ackermann function

def ackermann(m,n):
    if m == 0:
        return n+1
    if n == 0:
        return ackermann(m-1, 1)
    return ackermann(m-1, ackermann(m, n-1))

if __name__=='__main__':
    print ackermann(3, 4)

125


In [9]:
# Comma quibbling

def quibbled(sl):
    nsl = len(sl)
    if nsl == 0:
        return '{}'
    res = ''.join(sl[0])
    for i in range(1, nsl):
        if i == nsl-1:
            res += ' and '
        else:
            res += ', '
        res += sl[i]
    return '{' + res + '}'
    
if __name__=='__main__':
    print quibbled([])
    print quibbled(["ABC"])
    print quibbled(["ABC", "DEF"])
    print quibbled(["ABC", "DEF", "G", "H"])

{}
{ABC}
{ABC and DEF}
{ABC, DEF, G and H}


In [7]:
# continued fractions

def contfc(n):
    if n == 200:
        return 1.
    return 1. + 1. / (n + contfc(n+1))

def contfd(n):
    if n == 200:
        return 1.
    return n + (n + 1.) / (n + 2. + contfc(n+1))

if __name__=='__main__':
    print contfc(1)*5.
    print contfd(1)*4.

7.16563713361
5.85667000806


In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler

# Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data.
# For example, scale each attribute on the input vector X to [0, 1] or [-1, +1]. e.g. scaler = StandardScaler()
# Finding a reasonable regularization parameter  is best done using GridSearchCV,
# usually in the range 10.0 ** -np.arange(1, 7)
# Empirically, we observed that L-BFGS converges faster and with better solutions on small datasets.
# For relatively large datasets, however, Adam is very robust.

if __name__=='__main__':
    # X : array-like or sparse matrix, shape (n_samples, n_features)
    # y : array-like, shape (n_samples,) or (n_samples, n_outputs)
    X = [[0., 0., 0., 0., 0.], [1., 1., 1., 1., 1.]]
    y = [0, 1]
    
    X_train = [[0., 0., 0., 0., 0.], [1., 1., 1., 1., 1.]]
    X_test = [[0., 0., 0., 0., 0.], [1., 1., 2., 1., 1.]]
    scaler = StandardScaler() 
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test) 
    print X_test
    
    clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
    clf.fit(X, y)
    print clf.predict([[1., 1., 1., 0., 0.], [0., 0., 0., 0., 1.]])
    print clf.predict_proba([[1., 1., 1., 0., 0.], [0., 0., 0., 0., 1.]])
    print clf.score(X, y)

[[-1. -1. -1. -1. -1.]
 [ 1.  1.  3.  1.  1.]]
[1 0]
[[ 0.10225897  0.89774103]
 [ 0.97116002  0.02883998]]
1.0


In [16]:
# small LDA example for demo purposes
import random
import math
import time

def poissonrn(lda): # generate a poisson random number
    l = math.exp(-lda)
    k = 1.
    p = random.random()
    while p > l:
        k += 1.
        p *= random.random()
    return (k-1.)

def dirichlet(params): # sample dirichlet distribution
    sample = [random.gammavariate(a,1) for a in params]
    sample = [v/sum(sample) for v in sample]
    return sample

def partsct(doc): # find all parts of a document and count its respective occurance
    chklst = []
    ctlst = []
    for e in doc:
        if not e in chklst:
            chklst.append(e)
            ctlst.append(1)
        else:
            ctlst[chklst.index(e)] += 1
    return (chklst, ctlst)

def doc_parts_tbl(docs): # build a document-parts table
    ptslst = []
    for d in docs:
        ptslst.append(partsct(d)) 
    return ptslst

def all_parts(dbt): # a list of all parts in all docs, uniquely, from doc parts table
    apts = []
    for d in dbt:
        for de in d[0]:
            if not de in apts:
                apts.append(de)
    return apts

def parts_per_doc(lda): # pick how many parts you want per each composite (doc) - from Poisson distribution
    return poissonrn(lda)

def parts_topics(parts, topics, beta): # build the parts-topics table: for each column draw from Dirichlet distr.(beta)
    res = []
    betalst = []
    for p in parts:
        betalst.append(beta)
    for t in topics:
        res.append(dirichlet(betalst))
    return res

def comp_topics(docs, topics, alpha): # build the composites(docs)-topics table: for each row draw from Dirichlet distr.(alpha)
    res = []
    alphalst = []
    for t in topics:
        alphalst.append(alpha)
    for d in docs:
        res.append(dirichlet(alphalst))
    return res

def smpl_topbydoc(ndoc, doctop): # sample topic by document
    maxtop = 0.
    i = 0
    imax = 0
    for p in doctop[ndoc]:
        if p > maxtop:
            maxtop = p
            imax = i
        i += 1
    return imax

def smpl_partsbytop(ntop, parttop): # sample parts by topic
    maxprt = 0.
    i = 0
    imax = 0
    for p in parttop[ntop]:
        if p > maxprt:
            maxprt = p
            imax = i
        i += 1
    return imax

if __name__=='__main__':
    docs = []
    docs.append('aaaaa')
    docs.append('bbbbb')
    docs.append('ccccc')
    docs.append('aaaaabbbbbccccc')
    #print docs
    dbt = doc_parts_tbl(docs) # document and parts table
    #print dbt
    random.seed(time.clock())
    ntop = 3 # number of topics
    alpha = 0.2
    beta = 0.5
    #print dirichlet([beta, beta])
    apts = all_parts(dbt)
    parttop = parts_topics(apts, [0, 1, 2], beta)
    doctop = comp_topics(apts, docs, alpha)
    maxtop = smpl_topbydoc(0, doctop)
    npt = smpl_partsbytop(maxtop, parttop)
    print 'most representative part of doc 0: index %d : part %s' % (npt, apts[npt])

most representative part of doc 0: index 1 : part b


In [28]:
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
import numpy as np

def rnd_shelf(nsmpls, nspot, nprod, config):
    X = []
    y = []
    for k in range(nsmpls):
        xs = []
        for i in range(nspot):
            if config == 0:
                if i < nspot/2:
                    xs.append(1.)
                else:
                    xs.append(2.)
        X.append(xs)
        y.append(k % nsmpls)
    return (X, y)

# Multi-layer Perceptron is sensitive to feature scaling, so it is highly recommended to scale your data.
# For example, scale each attribute on the input vector X to [0, 1] or [-1, +1]. e.g. scaler = StandardScaler()
# Finding a reasonable regularization parameter  is best done using GridSearchCV,
# usually in the range 10.0 ** -np.arange(1, 7)
# Empirically, we observed that L-BFGS converges faster and with better solutions on small datasets.
# For relatively large datasets, however, Adam is very robust.

if __name__=='__main__':
    # X : array-like or sparse matrix, shape (n_samples, n_features)
    # y : array-like, shape (n_samples,) or (n_samples, n_outputs)
    #X = [[0., 0., 0., 0., 0.], [1., 1., 1., 1., 1.], [0., 1., 0., 1., 0.]]
    #X = np.random.rand(3,340)
    #y = [0, 1, 0]
    X, y = rnd_shelf(5, 340, 2, 0)
    
    clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
    clf.fit(X, y)
    print clf.predict(np.random.rand(1,340))
    print clf.predict_proba(np.random.rand(1,340))
    print clf.score(X, y)

[0]
[[ 0.19547634  0.19551008  0.20323978  0.20577707  0.19999673]]
0.2
