In [ ]:
import numpy as np

def levenshtein(seq1, seq2):  
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in xrange(size_x):
        matrix [x, 0] = x
    for y in xrange(size_y):
        matrix [0, y] = y

    for x in xrange(1, size_x):
        for y in xrange(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

if __name__=='__main__':
    print levenshtein('test', 'toast')

In [40]:
# tic-tac-toe minimax

def chkwin(bl,p): # check for win for board list
    for i in range(0,6,3):
        if bl[i]==p and bl[i+1]==p and bl[i+2]==p:
            return True
    for i in range(3):
        if bl[i]==p and bl[i+3]==p and bl[i+6]==p:
            return True
    if bl[0]==p and bl[4]==p and bl[8]==p:
            return True
    if bl[2]==p and bl[4]==p and bl[6]==p:
            return True
    return False

def otherp(p):
    if p==1:
        return 2
    return 1

def mvopt(bl): # returns movement options for current board state
    res = []
    for i in range(len(bl)):
        if bl[i]==0:
            res.append(i)
    return res

def plyrmv(bl,i,p): # next player move
    return [x if ind != i else p for ind, x in enumerate(bl)]

def successors(bl,p): # return all successor board states
    mo = mvopt(bl)
    succs = []
    for o in mo:
        succs.append([0,plyrmv(bl,o,p)]) # [value=0 (default utility), state]
    return succs

def util(bl,p): # return utility of current board for player p
    if chkwin(bl,p):
        return 1
    elif chkwin(bl,otherp(p)):
        return -1
    return 0

def maxval(bl,p): # determine the max-value for player p
    tt = util(bl,p)
    if tt != 0:
        return [tt,bl]
    v = [-1000,bl]
    succs = successors(bl,p)
    for s in succs:
        miv = minval(s[1],p)
        if miv[0] > v[0]:
            v = miv
    return v

def minval(bl,p): # determine the min-value for player p
    tt = util(bl,p)
    if tt != 0:
        return [tt,bl]
    v = [1000,bl]
    succs = successors(bl,otherp(p))
    for s in succs:
        mav = maxval(s[1],p)
        if mav[0] < v[0]:
            v = mav
    return v

def minimaxdec(bl,p): # minimax decision player p
    v = maxval(bl,p)
    return v

if __name__=='__main__':
    brd = [2,0,1,1,0,0,1,2,2]
    print minimaxdec(brd,1)

[1, [2, 0, 1, 1, 1, 0, 1, 2, 2]]


In [1]:
# dot test
import numpy as np

vec0 = np.array([[1], [2]])
vec1 = np.array([[1, 2]])

print np.dot(vec0, vec1)

[[1 2]
 [2 4]]


In [1]:
# Haiku generator
from random import randint

wordList1 = ["berauschend", "erstaunlich", "farbenfroh", "entzückend", "zarteste"]
wordList2 = ["Visionen", "Entfernung", "Gewissen", "Prozess", "Chaos"]
wordList3 = ["abergläubisch", "kontrastierend", "anmutig", "einladend", "widersprüchlich", "überwältigend"]
wordList4 = ["wahrer", "dunkler", "kalter", "warmer", "heller"]
wordList5 = ["Landschaft", "Jahreszeit", "Farben", "Licht", "Frühling", "Winter", "Sommer", "Herbst"]
wordList6 = ["unbestreitbare", "schöne", "unersetzliche", "unglaubliche", "unwiderrufliche"]
wordList7 = ["Inspiration", "Phantasie", "Weisheit", "Gedanken"]

wordIndex1=randint(0, len(wordList1)-1)
wordIndex2=randint(0, len(wordList2)-1)
wordIndex3=randint(0, len(wordList3)-1)
wordIndex4=randint(0, len(wordList4)-1)
wordIndex5=randint(0, len(wordList5)-1)
wordIndex6=randint(0, len(wordList6)-1)
wordIndex7=randint(0, len(wordList7)-1)

haiku = wordList1[wordIndex1] + " " + wordList2[wordIndex2] + ",\n" 
haiku = haiku + wordList3[wordIndex3] + " " + wordList4[wordIndex4] + " " + wordList5[wordIndex5]  + ",\n"
haiku = haiku + wordList6[wordIndex6] + " " + wordList7[wordIndex7] + "."

print(haiku)

entzückend Chaos,
kontrastierend kalter Landschaft,
unersetzliche Phantasie.


In [23]:
# matrix tests (against corresponding C-code)
import numpy as np

h = np.array([[1.,1.,1.,1.], [1.,1.,1.,1.], [1.,1.,1.,1.]])
dWz = np.array([[1.,1.,1.], [1.,1.,1.], [1.,1.,1.]])
dz = np.array([[1.,1.,1.]])
x = np.array([[1.],[1.],[1.]])

print h
print dWz
print np.dot(dWz.T, x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3.]
 [3.]
 [3.]]


In [2]:
zip([1,2,3], ['a', 'b', 'c'], [1,2,3])

[(1, 'a', 1), (2, 'b', 2), (3, 'c', 3)]

In [3]:
 
import math
 
def mandelbrot(z , c , n=40):
    if abs(z) > 1000:
        return float("nan")
    elif n > 0:
        return mandelbrot(z ** 2 + c, c, n - 1) 
    else:
        return z ** 2 + c
 
print("\n".join(["".join(["#" if not math.isnan(mandelbrot(0, x + 1j * y).real) else " "
                 for x in [a * 0.02 for a in range(-80, 30)]]) 
                 for y in [a * 0.05 for a in range(-20, 20)]])
     )
 

                                                                                #                             
                                                                                                              
                                                                                                              
                                                                       #  ##                                  
                                                                     ###########                              
                                                                    ############                              
                                                                     ##########                               
                                                            ##   # ############  # #   #                      
                                                    ###### # ########################### #                    
 

In [4]:
# a series

def sn(sn1, n):
    if sn1<n:
        return sn1+n
    return sn1-n

if __name__=='__main__':
    sn1 = 1
    for n in range(2,5000):
        sn1 = sn(sn1,n)
        if sn1 == 0:
            print 'n: %d -> Sn: %d' % (n, sn1)

n: 3 -> Sn: 0
n: 12 -> Sn: 0
n: 39 -> Sn: 0
n: 120 -> Sn: 0
n: 363 -> Sn: 0
n: 1092 -> Sn: 0
n: 3279 -> Sn: 0


In [5]:
# integer equations

def xx(y,z,t):
    return 3./z + 2.*t/z*yy(z,t)

def yy(z,t):
    return (z-3.*t)/(2*t*t+z*z)

def eq1(z,t):
    y = yy(z,t)
    return xx(y,z,t)*z - 2.*y*t

def eq2(z,t):
    y = yy(z,t)
    return xx(y,z,t)*t + y*z

if __name__=='__main__':
    for z in range(1,5):
        for t in range(1,5):
            if eq1(float(z),float(t))==3. and eq2(float(z),float(t))==1.:
                y = yy(z,t)
                x = xx(y,z,t)
                print 'x: %f y: %f z: %f t: %f' % (x, y, z, t)

x: 1.666667 y: -0.666667 z: 1.000000 t: 1.000000
x: 1.333333 y: -0.166667 z: 2.000000 t: 1.000000
x: 0.833333 y: -0.333333 z: 2.000000 t: 2.000000
x: 1.000000 y: 0.000000 z: 3.000000 t: 1.000000
x: 0.555556 y: -0.222222 z: 3.000000 t: 3.000000
x: 0.414634 y: -0.219512 z: 3.000000 t: 4.000000
x: 0.777778 y: 0.055556 z: 4.000000 t: 1.000000
x: 0.666667 y: -0.083333 z: 4.000000 t: 2.000000
x: 0.529412 y: -0.147059 z: 4.000000 t: 3.000000
x: 0.416667 y: -0.166667 z: 4.000000 t: 4.000000


In [3]:
import numpy as np

def kahansum(a):
    mysum = 0.0
    c = 0.0                       # A running compensation for lost low-order bits.
    for i in range(len(a)):
        y = a[i] - c              # So far, so good: c is zero.
        t = mysum + y             # Alas, sum is big, y small, so low-order digits of y are lost.
        c = (t - mysum) - y       # (t - sum) cancels the high-order part of y; subtracting y recovers negative (low part of y)
        mysum = t                 # Algebraically, c should always be zero. Beware overly-aggressive optimizing compilers!
    return mysum

if __name__=='__main__':
    tarr = np.random.rand(100)
    print kahansum(tarr)
    print np.sum(tarr)

52.11775858521866
52.11775858521867
