In [1]:
# gcd
def divisors(a):
    res = [x for x in range(1,a+1) if a % x == 0]
    return res

def gcd(a,b):
    if b > a:
        c = a
        a = b
        b = c
    an = a
    bn = b
    rn = 1
    while rn > 0:
        rn = an % bn
        an = bn
        bn = rn
    return an

def gcd_iter(u, v):
    while v:
        u, v = v, u % v
    return abs(u)

def gcd_bin(u, v):
    u, v = abs(u), abs(v) # u >= 0, v >= 0
    if u < v:
        u, v = v, u # u >= v >= 0
    if v == 0:
        return u
    # u >= v > 0
    k = 1
    while u & 1 == 0 and v & 1 == 0: # u, v - even
        u >>= 1; v >>= 1
        k <<= 1
    t = -v if u & 1 else u
    while t:
        while t & 1 == 0:
            t >>= 1
        if t > 0:
            u = t
        else:
            v = -t
        t = u - v
    return u * k

def redfrac(num, denom): # reduce fraction
    ndgcd = gcd_bin(num, denom)
    return [ num / ndgcd, denom / ndgcd ]

if __name__=='__main__':
    #print gcd(24,16)
    print redfrac(234, 766)

[117, 383]


In [59]:
# monetary system recursion

def fmon(x,ak): # number of ways you can represent x in terms of coins ak
    if len(ak) == 0:
        return 0
    a = ak[len(ak)-1]
    n = int( x / a )
    res = 1
    for k in range(1,n+1):
        res += fmon( k*a, ak[:-1] )
    return res

if __name__=='__main__':
    print fmon(100,[1,5,10,25])

231


In [17]:
# triangle along a curve
import math
import random
import os

def tarea(x0, x1, x2, func):
    y0 = func(x0)
    y1 = func(x1)
    y2 = func(x2)
    return abs((x1-x0)*(y2-y0) - (x2-x0)*(y1-y0))

if __name__=='__main__':
    #print tarea(0., 1., 2., math.sin)
    random.seed = (os.urandom(1024))
    nlim = 10000000
    tota = 0.
    for n in range(nlim):
        x0 = random.uniform(0., 2.*math.pi)
        x1 = random.uniform(0., 2.*math.pi)
        x2 = random.uniform(0., 2.*math.pi)
        tota += tarea(x0, x1, x2, math.sin)
    print tota / float(nlim) / 2.

0.668579804596


In [119]:
# an inequality
import matplotlib.pyplot as plt

def lefts(a,b,c,d):
    return 62208. * (a**7+b**7+c**7+d**7)**2

def rights(m, a,b,c,d):
    return m * (a**2+b**2+c**2+d**2)**7

def mm(a,b,c,d):
    return lefts(a,b,c,d) / (a**2+b**2+c**2+d**2)**7

if __name__=='__main__':
    a=6.
    b=6.
    #x = []
    #y = []
    #for ic in range(4,7):
        #c = float(ic)
        #d=-a-b-c
        #x.append(ic)
        #y.append(mm(a,b,c,d))
        #print '%d : %f' % (ic, mm(a,b,c,d))
    #_ = plt.plot(x, y, '-')
    #plt.show()
    c=6.
    d=-a-b-c
    print '%d : %f' % (ic, mm(a,b,c,d))

6 : 8281.000000


In [4]:
# monetary system recursion II

def fmon(x,ak): # number of ways you can represent x in terms of coins ak
    if len(ak) == 0:
        return 0
    a = ak[len(ak)-1]
    n = int( x / a )
    res = 1
    for k in range(1,n+1):
        res += fmon( k*a, ak[:-1] )
    return res

if __name__=='__main__':
    #print fmon(5378,[1,5,10,25,100,500,1000,2000])
    print fmon(53,[1,5,10,20])
    print fmon(78,[1,5,10,25])

35
110


In [8]:
# squares
import itertools

def checksum(l):
    if l[0]+l[1]+l[3]+l[4] != 20:
        return False
    if l[1]+l[2]+l[4]+l[5] != 20:
        return False
    if l[3]+l[4]+l[6]+l[7] != 20:
        return False
    if l[4]+l[5]+l[7]+l[8] != 20:
        return False
    if l[0]+l[2]+l[6]+l[8] != 20:
        return False
    if l[1]+l[3]+l[5]+l[7] != 20:
        return False
    return True

if __name__=='__main__':
    testl = list(itertools.permutations(range(1,10)))
    for e in testl:
        if checksum(e):
            print e
            break

(1, 6, 7, 8, 5, 2, 3, 4, 9)


In [48]:
# restaurant visits
import random

def qual(nvis,nrk,nprob):
    res = []
    hiq = 0
    for ivis in range(nvis):
        if ivis < nprob:
            thisrk = random.randint(1,nrk)
            res.append(thisrk)
            if thisrk > hiq:
                hiq = thisrk
        else:
            res.append(hiq)
    return res
            
if __name__=='__main__':
    random.seed()
    totr = 0.
    for n in range(1000):
        totr += sum(qual(4,5,2))/4.
    print totr / 1000.

3.35225


In [92]:
# regex tests
import re

dailybugle ='Spider-Man Menaces City!'
pattern = r'spider[- ]?man.' # r'' raw string syntax, [...] any char listed or in range, ? match 0 or 1 time, . any char

if re.match(pattern, dailybugle, re.IGNORECASE):
    print dailybugle

date = '12/30/1969'
regex = re.compile(r'^(\d\d)[-/](\d\d)[-/](\d\d(?:\d\d)?)$') # ^ start of string, (...) group subpatterns, \d digit char
# (?:...) non-capturing group, $ end of search string

mmatch = regex.match(date)
#print mmatch.string
if mmatch:
    month = mmatch.group(1)
    day = mmatch.group(2)
    year = mmatch.group(3)
    print mmatch.groups([0])
    print '%s %s %s' % (month, day, year)

date = "aaa_bbb"
regex = re.compile(r"(?:aaa)(_bbb)")
mmatch = regex.match(date)
if mmatch:
    print mmatch.groups([0])
#print re.findall(regex, date)
date = "111_222"
regex = re.compile(r"(?:111)(_222)")
mmatch = regex.match(date)
if mmatch:
    print mmatch.groups([0])
date = "111_222"
regex = re.compile(r"(?:111)(_\d\d\d)")
mmatch = regex.match(date)
if mmatch:
    print mmatch.groups([0])
date = "111_222"
regex = re.compile(r"(_\d\d\d)*")
mmatch = regex.match(date)
if mmatch:
    print mmatch.groups([0])

Spider-Man Menaces City!
('12', '30', '1969')
12 30 1969
('_bbb',)
('_222',)
('_222',)
([0],)


In [60]:
# Gated Recurrent Unit (GRU) test (Cho 2014):
import numpy as np

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def dtanh(x): # actually sech**2
    return 1.0 - np.tanh(x)**2

def forget_layer(combine):
    return sigmoid(np.dot(wr, np.transpose(combine)))
    
def update_layer(combine):
    return sigmoid(np.dot(wz, np.transpose(combine)))
    
def output_layer(htempt):
    return np.tanh(np.dot(w, htempt))
    
def GRU(prev_ht, xt): # a GRU forward propagation
    combine = np.add(prev_ht,xt)
    rt = forget_layer(combine)
    zt = update_layer(combine)
    htempt = np.add(np.multiply(rt, np.transpose(prev_ht)), np.transpose(xt))
    htempt = output_layer(htempt)
    ht = np.add((np.multiply(np.subtract(np.array([[1],[1],[1],[1]]), zt), np.transpose(prev_ht))), np.multiply(zt, htempt))
    return ht

if __name__ == '__main__':
    prev_ht = np.array([[1,1,0,0]])
    xt = np.array([[0,0,1,1]])
    
    wr = np.random.rand(4,4) - np.random.rand(4,4)
    wz = np.random.rand(4,4) - np.random.rand(4,4) # bias trick: last line - todo: add bias back!
    w = np.random.rand(4,4) - np.random.rand(4,4)

    np.set_printoptions(precision=3)
    
    print GRU(prev_ht, xt)

[[ 0.804]
 [ 0.867]
 [ 0.209]
 [-0.144]]


In [22]:
# Gated Recurrent Unit (GRU) test (Cho 2014) with backprop:
import numpy as np

def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    np.putmask(x, x > 100, 100) # limit array values of x (np.putmask(a, a >= m, m - 1))
    np.putmask(x, x < -100, -100)
    return 1/(1+np.exp(-x))

def dtanh(x): # actually sech**2
    return 1.0 - np.tanh(x)**2

def forget_layer(combine):
    return sigmoid(np.dot(wr, np.transpose(combine)))
    
def update_layer(combine):
    return sigmoid(np.dot(wz, np.transpose(combine)))
    
def output_layer(htempt):
    return np.tanh(np.dot(w, htempt))
    
def GRU(prev_ht, xt): # a GRU forward propagation
    combine = np.add(prev_ht,xt)
    rt = forget_layer(combine)
    zt = update_layer(combine)
    htempt = np.add(np.multiply(rt, np.transpose(prev_ht)), np.transpose(xt))
    htempt = output_layer(htempt)
    ht = np.add((np.multiply(np.subtract(np.array([[1],[1],[1],[1]]), zt), np.transpose(prev_ht))), np.multiply(zt, htempt))
    return ht

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0) # only difference

def forward(x, y, Uz, Ur, Uc, Wz, Wr, Wc, bz, br, bc, V, bV, s0):
    vocabularysize =len(x)
    sentencesize = len(x)
    iMemsize = len(V)
    s = np.zeros( (iMemsize, sentencesize) ) # np.zeros((nrows, ncols))
    yhat = np.zeros( (vocabularysize, sentencesize) )
    L = np.zeros( (sentencesize, 1) )
    z = np.zeros( (iMemsize, sentencesize) )
    r = np.zeros( (iMemsize, sentencesize) )
    c = np.zeros( (iMemsize, sentencesize) )
    
    # calculate result for step 1 since s 0 is not in s
    #tst0 = Wz.dot(np.transpose(s0))
    z = sigmoid( Uz.dot(x) + Wz.dot(np.transpose(s0)) + bz ) # np.multiply() equivalent to *
    r = sigmoid( Ur.dot(x) + Wr.dot(np.transpose(s0)) + br )
    c = np.tanh( Uc.dot(x) + Wc.dot(s0*r ) + bc )
    s = np.subtract(np.ones(len(z)),z)*c + z*s0 # .∗ = element-wise mult
    yhat = softmax( V.dot(s) + bV )
    L = sum(np.negative(y)*np.log( yhat ) )
    
    res = []
    res.append(s)
    res.append(yhat)
    res.append(L)
    res.append(z)
    res.append(r)
    res.append(c) # c==h
    
    #for wordI in range(2, sentencesize):
        #z[:, wordI] = sigmoid( Uz.dot(x[:,wordI]) + Wz.dot(s[:,wordI−1]) + bz )
        #r[:, wordI] = sigmoid( Ur.dot(x[:,wordI]) + Wr.dot(s[:,wordI−1]) + br )
        #c[:, wordI] = tanh( Uc.dot(x[:,wordI]) + Wc.dot(s[:,wordI−1]*r[:,wordI] ) + bc )
        #s[:, wordI] = np.subtract(np.ones(len(z)),z[:,wordI] )*c[:,wordI] + z[:,wordI]*s[:,wordI−1]
        #yhat[:, wordI] = softmax( V.dot(s[:,wordI]) + bV )
        #L(wordI) = sum(np.negative(y[:,wordI])*np.log( yhat[:,wordI] ) )
    return res

def backward_direct(x, y, Uz, Ur, Uc, Wz, Wr, Wc, bz, br, bc, V, bV, s0):
    
    fwddata = forward (x, y, Uz, Ur, Uc, Wz, Wr, Wc, bz, br, bc, V, bV, s0) # forward propagate
    # S-internal state, Yhat-predictions, L-losses, Z,R,C-intermediate results (C=H=ht)
    s=fwddata[0]
    yhat=fwddata[1]
    L=fwddata[2]
    z=fwddata[3]
    r=fwddata[4]
    c=fwddata[5] # actually h
    
    sentencesize = len(x)
    # calculate gradient using chain rule
    deltay = np.subtract(yhat, y) # output y_hat - truth y
    dbV = np.sum( deltay, 1 )
    dV = np.zeros( len(V) )
    for wordI in range(1, sentencesize):
        dV = dV + np.dot(deltay[:, wordI], s[:, wordI]) # calculate dL/dS=VT(yhat-y)
    
    ds0 = np.zeros( len(s0) ) # initialize weight increments with 0s 
    dUc = np.zeros( len(Uc) )
    dUr = np.zeros( len(Ur) )
    dUz = np.zeros( len(Uz) )
    dWc = np.zeros( len(Wc) )
    dWr = np.zeros( len(Wr) )
    dWz = np.zeros( len(Wz) )
    dbz = np.zeros( len(bz) )
    dbr = np.zeros( len(br) )
    dbc = np.zeros( len(bc) ) # c==h
    dssingle = np.dot(np.transpose(V), deltay) # ' = transpose; V*(yhat-y) : single state change from difference truth-predctn
    
    dscur = np.zeros((len(dssingle),1)) # np.zeros((2, 1)) - array([[ 0.], [ 0.]]) : current state change
    
    for wordJ in range(sentencesize-1, 1, -1): # index t : counting down from nw=sentencesize
        wordJm1 = wordJ-1
        
        # A(:,3) is the 3rd column of A -> numpy: test[:,0] cols, test[1,:] rows
        dscur = dscur + dssingle[:, wordJ] # current state change ds
        dscurbk = dscur # backup of current state change

        # dtanhInput = ds*(1-zt)*(1-ht)*ht (should be: ds*(1-zt)*(1-ht)*(1+ht) - derivative of tanh is 1-tanh**2 )
        dtanhInput = dscur*(np.subtract(np.ones((len(z),1)),z))*(np.subtract(np.ones((len(z),1)),c[:, wordJ]*c[:, wordJ] ))
        dbc = dbc + dtanhInput
        dUc = dUc + dtanhInput.dot(x) # ds*(1-zt)*(1-ht)*ht*xt
        
        dWc = dWc + dtanhInput.dot(s*r) # ds*(1-zt)*(1-ht)*ht*st-1*rt
        dsr = np.dot(np.transpose(Wc), dtanhInput) # ' = transpose
        dscur = dsr*r
        dsigInputr = dsr*s*r*(np.subtract(np.ones((len(r),1)),r)) # dsr*(st-1)*rt*(1-rt)
        dbr = dbr + dsigInputr
        dUr = dUr + dsigInputr.dot(x) # dsr*(st-1)*rt*(1-rt)*xt

        dWr = dWr + np.dot(dsigInputr, s) # dsr*(st-1)*rt*(1-rt)*(st-1)
        dscur = dscur + np.dot(np.transpose(Wr), dsigInputr) # Wr*dsr*(st-1)*rt*(1-rt)
        dscur = dscur + dscurbk*z
        dz = dscurbk*( np.subtract(s, c) ) # ds*(st-1 - ht)
        dsigInputz = dz*z*(np.subtract(np.ones((len(z),1)),z)) # dz*zt*(1-zt)
        dbz = dbz + dsigInputz
        dUz = dUz + dsigInputz.dot(x) # dz*zt*(1-zt)*xt

        dWz = dWz + dsigInputz.dot(s)
        dscur = dscur + np.dot(np.transpose(Wz), dsigInputz)
    
    dscur = dscur + dssingle[:,1]
    dtanhInput = ( dscur*(np.subtract(np.ones((len(z),1)), z))*(np.subtract(np.ones((len(c),1)), c[:,1]*c[:,1] ) ))
    dbc = dbc + dtanhInput
    dUc = dUc + dtanhInput.dot(x)
    
    dWc = dWc + np.dot(dtanhInput, ( s0*r ))
    dsr = np.dot(np.transpose(Wc), dtanhInput)
    ds0 = ds0 + dsr*r
    dsigInputr = dsr*s0*r*(np.subtract(np.ones((len(r),1)),r))
    dbr = dbr + dsigInputr
    dUr = dUr + dsigInputr.dot(x)
    
    dWr = dWr + s0.dot(dsigInputr)
    ds0 = ds0 + np.dot(np.transpose(Wr), dsigInputr)
    ds0 = ds0 + dscur*z
    dz = dscur*( np.subtract(s0, c) )
    dsigInputz = dz*z*(np.subtract(np.ones((len(z),1)),z))
    dbz = dbz + dsigInputz
    dUz = dUz + dsigInputz.dot(x)
    
    dWz = dWz + s0.dot(dsigInputr)
    ds0 = ds0 + np.dot(np.transpose(Wz), dsigInputz)
    return ds0

        
if __name__ == '__main__':
    # dimensions
    D = 4 # input dimensions
    H = 2 # hidden dimensions
    N = 4 # minibatch size
    
    prev_ht = np.transpose(np.array([[1,1,0,0]]))
    xt = np.transpose(np.array([[0,0,1,1]]))
    yt = np.transpose(np.array([[0,0,0,1]]))
    
    ur = np.random.rand(4,4) - np.random.rand(4,4)
    uz = np.random.rand(4,4) - np.random.rand(4,4)
    uc = np.random.rand(4,4) - np.random.rand(4,4)
    
    wr = np.random.rand(4,4) - np.random.rand(4,4)
    wz = np.random.rand(4,4) - np.random.rand(4,4) 
    wc = np.random.rand(4,4) - np.random.rand(4,4)
    
    br = np.random.rand(4,1) - np.random.rand(4,1)
    bz = np.random.rand(4,1) - np.random.rand(4,1)
    bc = np.random.rand(4,1) - np.random.rand(4,1)
    
    V = np.random.rand(4,4) - np.random.rand(4,4)
    bv = np.random.rand(4,1) - np.random.rand(4,1)
    
    s0 = np.array([[0,0,0,0]])

    np.set_printoptions(precision=3)
    
    #print forward(xt, yt, uz, ur, uc, wz, wr, wc, bz, br, bc, V, bv, s0)
    print backward_direct(xt, yt, uz, ur, uc, wz, wr, wc, bz, br, bc, V, bv, s0)

[[ 0.443 -0.368 -0.496 -0.355]
 [ 0.339 -0.287 -0.401 -0.332]
 [ 0.245 -0.21  -0.3   -0.269]
 [ 0.236 -0.202 -0.29  -0.265]]
