In [9]:

# NN maths simple example

import numpy as np


ninputs = 64
noutputs = 2
nhidden0 = 8

ainputs = np.random.random((ninputs,))
bhidden0 = np.array((nhidden0,))
coutputs = np.array((noutputs,))

winphidden0 = np.zeros((ninputs, nhidden0))
whidden0out = np.zeros((nhidden0, noutputs))

winphidden0idt = np.identity(nhidden0, like=winphidden0)
whidden0outidt = np.identity(nhidden0, like=whidden0out)

winphidden0idt

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [3]:

import time

print('.', end='\r')

time.sleep(1.5)

print('+', end='\r')
print()
   

+


In [39]:

import random
import time

guessthis = [str(random.randint(0, 9)) for i in range(6)]

time.sleep(0.8)
for el in guessthis:
    print(el, end='\r')
    time.sleep(1.2)
    print(' ', end='\r')
    time.sleep(0.2)
    
print()

guessednumber = input("Enter the number: ")

if guessednumber == ''.join(guessthis):
    print('correct')
else:
    print('incorrect', ''.join(guessthis))
    

Enter the number:  648024


correct


In [2]:
import random
import time

lenguess = 6

guessthis = [str(random.randint(0, 9)) for i in range(lenguess)]

time.sleep(0.8)
for el in guessthis:
    print(el, end='\r')
    time.sleep(1.2)
    print(' ', end='\r')
    time.sleep(0.2)
    
print()

modifier = random.randint(1, 9)
idxmodifier = random.randint(0, lenguess-1)

print(f"Add {modifier} to the {idxmodifier+1}. number.")
guessthis[idxmodifier] = str(int(guessthis[idxmodifier]) + modifier)

guessednumber = input("Enter the number: ")

if guessednumber == ''.join(guessthis):
    print('correct')
else:
    print('incorrect', ''.join(guessthis))
    

 
Add 1 to the 3. number.


Enter the number:  038134


correct


In [1]:
x = 1
eval('x + 1')

#eval('x')


2

In [2]:
import random

random.choice([1, 2, 3])

2

In [21]:
from numpy import exp, array, random, dot

training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

random.seed(1)

synaptic_weights = 2 * random.random((3, 1)) - 1

for iteration in range(1000):
    output = 1 / (1 + exp(-(dot(training_set_inputs, synaptic_weights))))
    synaptic_weights += dot(training_set_inputs.T, (training_set_outputs - output) * output * (1 - output))  # quadratic loss
    
print(1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights)))))

[0.99929937]


In [314]:
from numpy import exp, array, random, dot

training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

#random.seed(1)

synaptic_weights = 2 * random.random((3, 1)) - 1

for iteration in range(10):
    output = 1 / (1 + exp(-(dot(training_set_inputs, synaptic_weights))))
    synaptic_weights += dot(training_set_inputs.T, (training_set_outputs - output))  # cross entropy loss
    
print(1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights)))))

[0.98404014]


In [188]:
from numpy import exp, array, random, dot

training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

t_input = array([0, 0, 1])
t_output = array([0])

random.seed(1)

synaptic_weights = 2 * random.random((3, 1)) - 1

for iteration in range(100):
    output = 1 / (1 + exp(-(dot(t_input, synaptic_weights))))
    synaptic_weights += dot(t_input.T, array([1, 1, 1]) * (t_output - output) * output * (1 - output))
    
print(1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights)))))

[0.16077543]


In [385]:
from numpy import exp, array, random, dot

training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

t_input = array([0, 0, 1])
t_output = array([0])

random.seed(1)

synaptic_weights = 2 * random.random((3, 1)) - 1

for iteration in range(100):
    output = 1 / (1 + exp(-(dot(t_input, synaptic_weights))))
    synaptic_weights += dot(t_input.T, array([1, 1, 1]) * (t_output - output))  # cross entropy loss
    
print(1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights)))))

[0.02232899]


$$c = \sqrt{a^2 + b^2}$$

In [395]:
from numpy import exp, array, random, dot, max

training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

etha = 1.
synaptic_weights = 2 * random.random((3, 1)) - 1  # 3 weights + bias

for iteration in range(100):
    tmpdot = 0
    i = random.randint(4)
    t_input = array([training_set_inputs[i]])
    t_output = training_set_outputs[i]
    tmpdot += (dot(t_input, synaptic_weights))
    output = 1 / (1 + exp(-tmpdot))
    synaptic_weights += etha * t_input.T * (t_output - output)  # cross entropy loss
    
for i in range(4):
    print(i, training_set_inputs[i], training_set_outputs[i], 1 / (1 + exp(-(dot(training_set_inputs[i], synaptic_weights)))))

print(1 / (1 + exp(-(dot(array([1, 0, 0]), synaptic_weights)))))

0 [0 0 1] [0] [0.05248225]
1 [1 1 1] [1] [0.94024712]
2 [1 0 1] [1] [0.95228751]
3 [0 1 1] [0] [0.04184173]
[0.99723251]


**Core Concepts Illustrated**

The code demonstrates the three fundamental steps of the attention mechanism:

**Similarity Scores (Dot Product)**: The np.dot(keys, query) step calculates how relevant each Key is to the Query. A larger dot product means greater similarity.

**Attention Weights (Softmax)**: The Softmax function $\left(\frac{e^{score_i}}{\sum_j e^{score_j}}\right)$ is applied to the raw scores. This step normalizes the scores into a probability distribution, ensuring all weights are between 0 and 1 and sum up to 1. These weights indicate how much to pay attention to each value.

**Context Vector (Weighted Sum)**: The final output is computed by multiplying each Value by its corresponding Weight and summing the results ($\sum_{i} W_i \cdot V_i$). The resulting Context Vector is a representation that captures the most relevant information from the Values, steered by the Query.

In [396]:
import numpy as np

def simple_attention(query, keys, values):
    """
    A simplified, illustrative example of the attention mechanism.

    Args:
        query (np.ndarray): The vector representing what we're looking for.
        keys (np.ndarray): A set of vectors to compare the query against.
        values (np.ndarray): The values associated with the keys.

    Returns:
        np.ndarray: The context vector (weighted sum of values).
    """
    # 1. Calculate Similarity Scores (e.g., Dot Product)
    # The dot product measures how related the query is to each key.
    # Scores shape will be (num_keys,)
    scores = np.dot(keys, query)

    # 2. Normalize Scores to get Attention Weights (using Softmax)
    # Softmax converts scores into probabilities (weights) that sum to 1.
    # The higher the score, the higher the weight.
    # Weights shape will be (num_keys,)
    # np.exp(scores - np.max(scores)) is used for numerical stability
    exp_scores = np.exp(scores - np.max(scores))
    weights = exp_scores / np.sum(exp_scores)

    # 3. Compute Context Vector (Weighted Sum of Values)
    # The final output (context vector) is the sum of (weight * value).
    # This vector represents the "attended" information.
    # values shape is (num_keys, value_dim), weights shape is (num_keys,)
    # This results in (value_dim,)
    context_vector = np.dot(weights, values)

    return context_vector, weights

# --- Example Usage ---

# Define the input data:
# Here, the dimension for Q, K, V is 4. We have 3 key-value pairs.
# Imagine Q is a word, and K/V are surrounding words.

# The Query (Q): What we are looking for (e.g., current word's embedding)
query = np.array([1.0, 0.5, 0.1, 0.0]) # Shape (4,)

# The Keys (K): What we compare against (e.g., other words' embeddings)
keys = np.array([
    [1.1, 0.4, 0.0, 0.1],  # Key 1: Very similar to Q
    [0.2, 0.8, 0.9, 0.7],  # Key 2: Less similar
    [0.9, 0.6, 0.1, 0.0]   # Key 3: Similar
]) # Shape (3, 4)

# The Values (V): The actual information to be aggregated
# (In self-attention, K and V are often the same, but they don't have to be)
values = np.array([
    [5.0, 5.0, 5.0, 5.0],  # Value 1 (High relevance expected)
    [1.0, 1.0, 1.0, 1.0],  # Value 2 (Low relevance expected)
    [3.0, 3.0, 3.0, 3.0]   # Value 3 (Medium relevance expected)
]) # Shape (3, 4)

# Run the attention mechanism
context_vector, weights = simple_attention(query, keys, values)

print("--- Simple Attention Example ---")
print(f"Query: {query}")
print("-" * 35)

print(f"Keys (K):\n{keys}")
print(f"Values (V):\n{values}")
print("-" * 35)

print(f"Attention Weights (W):\n{weights}")
# Expected: weights[0] and weights[2] should be high because Key 1 and Key 3 
# are more similar to the Query than Key 2.
print("-" * 35)

print(f"Context Vector (Output):\n{context_vector}")
# Expected: The output should be a blend of the values, dominated by Value 1 
# and Value 3 due to their higher weights.

--- Simple Attention Example ---
Query: [1.  0.5 0.1 0. ]
-----------------------------------
Keys (K):
[[1.1 0.4 0.  0.1]
 [0.2 0.8 0.9 0.7]
 [0.9 0.6 0.1 0. ]]
Values (V):
[[5. 5. 5. 5.]
 [1. 1. 1. 1.]
 [3. 3. 3. 3.]]
-----------------------------------
Attention Weights (W):
[0.40695369 0.22111864 0.37192767]
-----------------------------------
Context Vector (Output):
[3.3716701 3.3716701 3.3716701 3.3716701]


**Hierarchical Attention** is an extension of the standard attention mechanism used in deep learning, primarily designed to process information with an inherent, nested structure, such as documents, which are composed of sentences, which are in turn composed of words.

It works by applying the attention mechanism at multiple levels of granularity:

### 1. The Concept

Instead of calculating a single context vector for the entire input sequence, Hierarchical Attention applies attention sequentially:

1.  **Lower Level (e.g., Word-to-Sentence Attention):** It first processes the elements at the lowest level (e.g., words in a sentence) and computes an intermediate representation (e.g., a **sentence vector**) by selectively weighing the importance of individual words.
2.  **Higher Level (e.g., Sentence-to-Document Attention):** These intermediate representations (sentence vectors) are then processed at the higher level. The mechanism selectively weighs the importance of these elements (sentences) to form the final, high-level output (e.g., a **document vector** or final prediction).

This multi-layered approach allows the model to first figure out which **words are important within a sentence** and then figure out which **sentences are important within the document**, leading to more robust and context-aware representations.

***

### 2. Key References

The seminal work introducing and popularizing this specific architecture is:

* **Yang, Z., Yang, D., Cohen, S., Salakhutdinov, R., & Hovy, E. (2016). Hierarchical Attention Networks for Document Classification.** *Proceedings of the 2016 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies (NAACL).*
    * **Focus:** This paper introduced the **Hierarchical Attention Network (HAN)** model, specifically for document classification, which is the standard implementation of hierarchical attention.

Other related and foundational works on attention include:

* **Bahdanau, D., Cho, K., & Bengio, Y. (2014). Neural machine translation by jointly learning to align and translate.** *International Conference on Learning Representations (ICLR).*
    * **Focus:** The original introduction of the **attention mechanism** (additive attention) in the context of sequence-to-sequence models (Neural Machine Translation).

* **Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A. N., ... & Polosukhin, I. (2017). Attention Is All You Need.** *Advances in Neural Information Processing Systems (NeurIPS).*
    * **Focus:** Introduced the **Transformer** architecture and the **Self-Attention** (or scaled dot-product attention) mechanism, which underpins modern models and is often adapted for hierarchical applications.

💡 BPE Overview
Byte Pair Encoding is a subword tokenization technique used to balance between character-level and word-level models.

Goal: Efficiently handle a large vocabulary and the "out-of-vocabulary" (OOV) problem, especially common with large language models (LLMs).

Process:

Start by treating every character as an initial token.

Iteratively find the most frequent adjacent pair of tokens (which can be characters or already-merged subwords).

Replace all occurrences of that pair with a new, single token.

Repeat the process for a fixed number of merge operations or until no more frequent pairs exist.

The provided Python code illustrates these steps by tracking tokens as space-separated strings and using a Counter to find the most frequent pairs.

This video provides an excellent, detailed explanation of how Byte Pair Encoding works, which is highly relevant to understanding the code. Lecture 8: The GPT Tokenizer: Byte Pair Encoding

In [400]:
from collections import Counter

def get_pair_counts(tokens):
    """Count the frequency of adjacent pairs in a list of tokens."""
    counts = Counter()
    for word, freq in tokens.items():
        token_list = word.split(' ')
        for i in range(len(token_list) - 1):
            pair = (token_list[i], token_list[i+1])
            counts[pair] += freq
    return counts

def merge_pair(tokens, pair, new_token):
    """Replace all occurrences of a pair in the token list with a new token."""
    merged_tokens = {}
    bigram_str = ' '.join(pair)
    new_str = new_token
    
    for word, freq in tokens.items():
        # Replace the pair with the new token, maintaining token separation
        # using a simple string replacement on the space-separated tokens.
        new_word = word.replace(bigram_str, new_str)
        merged_tokens[new_word] = freq
    return merged_tokens

def train_bpe(corpus, num_merges):
    """Main BPE training function."""
    
    # 1. Initial Tokens: Split each word into characters and track word frequencies.
    # The dictionary keys represent space-separated tokens (e.g., "h e l l o"), 
    # and the values are the frequencies of the *words* in the corpus.
    tokens = Counter(corpus.split())
    tokens = {' '.join(list(k)) : v for k, v in tokens.items()}
    
    print("Initial Vocabulary:", sorted(list(set(' '.join(tokens.keys()).split(' ')))) )
    print("-" * 20)

    merges = {}
    for i in range(num_merges):
        # 2. Find the most frequent pair
        pair_counts = get_pair_counts(tokens)
        if not pair_counts:
            break
            
        # Get the most frequent pair
        best_pair = pair_counts.most_common(1)[0][0]
        
        # 3. Create a new token (merge)
        new_token = ''.join(best_pair)
        merges[best_pair] = new_token
        
        # 4. Apply the merge to the corpus
        tokens = merge_pair(tokens, best_pair, new_token)
        
        print(f"Merge {i+1}: Merged {best_pair} into '{new_token}'")
        print("Current Tokens (word: frequency):", tokens)
        print("Current Vocabulary:", sorted(list(set(' '.join(tokens.keys()).split(' ')))) )
        print("-" * 20)
        
    return merges

# --- Example Usage ---
corpus = "low lower newest newest newest wide wide"
num_merges = 5

print(f"Starting BPE training on: '{corpus}' for {num_merges} merges.\n")
learned_merges = train_bpe(corpus, num_merges)

print("Final Learned Merges:", learned_merges)

Starting BPE training on: 'low lower newest newest newest wide wide' for 5 merges.

Initial Vocabulary: ['d', 'e', 'i', 'l', 'n', 'o', 'r', 's', 't', 'w']
--------------------
Merge 1: Merged ('w', 'e') into 'we'
Current Tokens (word: frequency): {'l o w': 1, 'l o we r': 1, 'n e we s t': 3, 'w i d e': 2}
Current Vocabulary: ['d', 'e', 'i', 'l', 'n', 'o', 'r', 's', 't', 'w', 'we']
--------------------
Merge 2: Merged ('n', 'e') into 'ne'
Current Tokens (word: frequency): {'l o w': 1, 'l o we r': 1, 'ne we s t': 3, 'w i d e': 2}
Current Vocabulary: ['d', 'e', 'i', 'l', 'ne', 'o', 'r', 's', 't', 'w', 'we']
--------------------
Merge 3: Merged ('ne', 'we') into 'newe'
Current Tokens (word: frequency): {'l o w': 1, 'l o we r': 1, 'newe s t': 3, 'w i d e': 2}
Current Vocabulary: ['d', 'e', 'i', 'l', 'newe', 'o', 'r', 's', 't', 'w', 'we']
--------------------
Merge 4: Merged ('newe', 's') into 'newes'
Current Tokens (word: frequency): {'l o w': 1, 'l o we r': 1, 'newes t': 3, 'w i d e': 2}
Cu

the key question here is the levels of attention and concepts: byte pairs -> words -> sentences -> documents are obvious, but I think there is a concept layer between sentences and documents. How, then, about higher and more abstract concept layers? Can this be done dynamically? What is the separation criterion? I imagine someting like information gain as used as a split criterion in random trees.


The Information Gain (IG) criterion is a key metric used in training Decision Trees to decide which attribute (feature) to split the data on at each node. Its goal is to maximize the purity of the resulting child nodes, meaning the children should ideally contain data points belonging to a single class.🌳 Information Gain ExplainedInformation Gain is calculated by finding the difference between the entropy of the parent node (before the split) and the weighted average of the entropy of the child nodes (after the split).$$IG(\text{S}, \text{A}) = \text{Entropy}(\text{S}) - \sum_{v \in \text{Values}(\text{A})} \frac{|\text{S}_v|}{|\text{S}|} \text{Entropy}(\text{S}_v)$$Where:$S$ is the set of data at the parent node.$A$ is the attribute being considered for the split.$\text{Values}(A)$ is the set of possible values for attribute $A$.$S_v$ is the subset of $S$ where attribute $A$ has value $v$.$|S|$ and $|S_v|$ are the number of elements in the respective sets.Entropy ($\text{Entropy}(S)$): This is a measure of the impurity or randomness in the data. Low entropy means the data is mostly of one class (pure), and high entropy means the classes are mixed (impure). The goal of a split is to reduce this value.$$\text{Entropy}(S) = - \sum_{i=1}^{c} p_i \log_2(p_i)$$Where $c$ is the number of classes, and $p_i$ is the proportion of samples belonging to class $i$.Information Gain: The split that results in the highest Information Gain is chosen because it is the most effective at reducing impurity and making the resulting subsets (children) purer.

In [407]:
import numpy as np

# 1. Define Entropy Function
def calculate_entropy(class_counts):
    """Calculates entropy given a list of class counts."""
    total_samples = sum(class_counts)
    if total_samples == 0:
        return 0
    
    entropy = 0
    for count in class_counts:
        # p_i is the proportion of the class
        p_i = count / total_samples
        if p_i > 0:
            # - p_i * log2(p_i)
            entropy -= p_i * np.log2(p_i)
    return entropy

# 2. Sample Data (Parent Node)
# The data has two classes: [Class A, Class B]
parent_counts = [5, 5]  # 5 A's and 5 B's (Total 10)
entropy_parent = calculate_entropy(parent_counts)
# Entropy here will be 1.0 (maximum impurity)

# 3. Define a Hypothetical Split (Feature 'Color' with values 'Red' and 'Blue')
# Split 1 (Red): [4 A's, 1 B] -> 5 samples
split_red_counts = [4, 1]
entropy_red = calculate_entropy(split_red_counts)

# Split 2 (Blue): [1 A, 4 B's] -> 5 samples
split_blue_counts = [1, 4]
entropy_blue = calculate_entropy(split_blue_counts)

# 4. Calculate Weighted Average Entropy of Children
total_samples = sum(parent_counts)
weighted_child_entropy = (
    (sum(split_red_counts) / total_samples) * entropy_red +
    (sum(split_blue_counts) / total_samples) * entropy_blue
)

# 5. Calculate Information Gain
information_gain = entropy_parent - weighted_child_entropy

print(f"Parent Entropy: {entropy_parent:.3f}")
print(f"Weighted Child Entropy: {weighted_child_entropy:.3f}")
print(f"Information Gain: {information_gain:.3f}") 

# The highest IG value indicates the best split.


Parent Entropy: 1.000
Weighted Child Entropy: 0.722
Information Gain: 0.278


In [401]:
# Hierarchical Attention

import numpy as np

def simple_attention(query, keys, values):
    """
    A simplified, illustrative example of the attention mechanism.

    Args:
        query (np.ndarray): The vector representing what we're looking for.
        keys (np.ndarray): A set of vectors to compare the query against.
        values (np.ndarray): The values associated with the keys.

    Returns:
        np.ndarray: The context vector (weighted sum of values).
    """
    # 1. Calculate Similarity Scores (e.g., Dot Product)
    # The dot product measures how related the query is to each key.
    # Scores shape will be (num_keys,)
    scores = np.dot(keys, query)

    # 2. Normalize Scores to get Attention Weights (using Softmax)
    # Softmax converts scores into probabilities (weights) that sum to 1.
    # The higher the score, the higher the weight.
    # Weights shape will be (num_keys,)
    # np.exp(scores - np.max(scores)) is used for numerical stability
    exp_scores = np.exp(scores - np.max(scores))
    weights = exp_scores / np.sum(exp_scores)

    # 3. Compute Context Vector (Weighted Sum of Values)
    # The final output (context vector) is the sum of (weight * value).
    # This vector represents the "attended" information.
    # values shape is (num_keys, value_dim), weights shape is (num_keys,)
    # This results in (value_dim,)
    context_vector = np.dot(weights, values)

    return context_vector, weights

# --- Example Usage ---



#  here we have to expand: the issue is not the attention mechanism, its the hierarchy definition and aggregation













# Define the input data:
# Here, the dimension for Q, K, V is 4. We have 3 key-value pairs.
# Imagine Q is a word, and K/V are surrounding words.

# The Query (Q): What we are looking for (e.g., current word's embedding)
query = np.array([1.0, 0.5, 0.1, 0.0]) # Shape (4,)

# The Keys (K): What we compare against (e.g., other words' embeddings)
keys = np.array([
    [1.1, 0.4, 0.0, 0.1],  # Key 1: Very similar to Q
    [0.2, 0.8, 0.9, 0.7],  # Key 2: Less similar
    [0.9, 0.6, 0.1, 0.0]   # Key 3: Similar
]) # Shape (3, 4)

# The Values (V): The actual information to be aggregated
# (In self-attention, K and V are often the same, but they don't have to be)
values = np.array([
    [5.0, 5.0, 5.0, 5.0],  # Value 1 (High relevance expected)
    [1.0, 1.0, 1.0, 1.0],  # Value 2 (Low relevance expected)
    [3.0, 3.0, 3.0, 3.0]   # Value 3 (Medium relevance expected)
]) # Shape (3, 4)

# Run the attention mechanism
context_vector, weights = simple_attention(query, keys, values)

print("--- Simple Attention Example ---")
print(f"Query: {query}")
print("-" * 35)

print(f"Keys (K):\n{keys}")
print(f"Values (V):\n{values}")
print("-" * 35)

print(f"Attention Weights (W):\n{weights}")
# Expected: weights[0] and weights[2] should be high because Key 1 and Key 3 
# are more similar to the Query than Key 2.
print("-" * 35)

print(f"Context Vector (Output):\n{context_vector}")
# Expected: The output should be a blend of the values, dominated by Value 1 
# and Value 3 due to their higher weights.

--- Simple Attention Example ---
Query: [1.  0.5 0.1 0. ]
-----------------------------------
Keys (K):
[[1.1 0.4 0.  0.1]
 [0.2 0.8 0.9 0.7]
 [0.9 0.6 0.1 0. ]]
Values (V):
[[5. 5. 5. 5.]
 [1. 1. 1. 1.]
 [3. 3. 3. 3.]]
-----------------------------------
Attention Weights (W):
[0.40695369 0.22111864 0.37192767]
-----------------------------------
Context Vector (Output):
[3.3716701 3.3716701 3.3716701 3.3716701]


A **Convolutional Network (ConvNet or CNN)** is a class of deep neural networks primarily designed to process data with a known grid-like topology, such as images (2D grid of pixels) or time-series data (1D grid). 🖼️
The core idea is to automatically and efficiently learn spatial hierarchies of features from the raw input data.

Key Components and Concepts
CNNs gain their power from three types of specialized layers:

1. **Convolutional Layer (The Core)**
This layer applies a learnable set of filters (also called kernels) across the input image.
Filter (Kernel): A small matrix (e.g., 3x3) that slides over the input (a process called convolution).
Feature Mapping: At each location, the filter computes a dot product between its values and the corresponding values of the input. This result is stored in an output structure called a feature map.
Feature Learning: Different filters learn to recognize different basic features, such as edges, textures, or corners, regardless of where they appear in the image (this is called translation invariance).

3. **Pooling Layer (Downsampling)**
This layer systematically reduces the spatial size (width and height) of the feature maps, which serves two main purposes:
Reduces Complexity: Lowers the number of parameters and computation in the network.
Increases Robustness: Makes the model less sensitive to minor shifts or distortions in the input image.
Max Pooling: The most common form, which takes the maximum value from a small window (e.g., 2x2) in the feature map.


5. **Fully Connected (FC) Layer (Classification)**
After several stacked Conv and Pooling layers have extracted high-level features, the feature maps are flattened into a single vector. This vector is then fed into one or more standard fully connected layers, which perform the final classification (e.g., determining if the image is a cat, dog, or bird).

In [398]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# --- 1. Define the CNN Architecture (The Model) ---
class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        # 1. Convolutional Layer 1
        # Input: 1 channel (grayscale), Output: 32 feature maps, 3x3 kernel
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, padding=1)

        # 2. Convolutional Layer 2
        # Input: 32 feature maps, Output: 64 feature maps, 3x3 kernel
        self.conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

        # 3. Pooling Layer
        # Reduces spatial size (2x2 window)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)

        # 4. Fully Connected (Dense) Layer
        # The size 7*7*64 comes from:
        # 28x28 (input) -> 14x14 (after pool1) -> 7x7 (after pool2) * 64 channels
        self.fc1 = nn.Linear(7 * 7 * 64, 128)

        # 5. Output Layer (10 classes for digits 0-9)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        # Apply Conv1 -> ReLU -> Pool
        x = self.pool(F.relu(self.conv1(x)))

        # Apply Conv2 -> ReLU -> Pool
        x = self.pool(F.relu(self.conv2(x)))

        # Flatten the feature maps for the Dense layers
        x = x.view(-1, 7 * 7 * 64)

        # Apply FC1 -> ReLU
        x = F.relu(self.fc1(x))

        # Output Layer (No softmax here; it's usually included in the loss function in PyTorch)
        x = self.fc2(x)
        return x

# --- 2. Data Loading and Preprocessing ---
# Define a standard transformation: convert to tensor and normalize
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)) # Standard MNIST mean and std
])

# Download and load the datasets
train_dataset = datasets.MNIST('./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST('./data', train=False, transform=transform)

# Create DataLoaders (for batching and shuffling)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=1000, shuffle=False)

# --- 3. Model Initialization, Loss, and Optimizer ---
model = SimpleCNN()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
epochs = 5

# --- 4. Training Loop ---
print("Starting PyTorch CNN Training...")
for epoch in range(1, epochs + 1):
    model.train() # Set the model to training mode
    running_loss = 0.0
    for batch_idx, (data, target) in enumerate(train_loader):
        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass: compute predicted outputs
        output = model(data)

        # Calculate the loss
        loss = criterion(output, target)

        # Backward pass: compute gradient of the loss w.r.t model parameters
        loss.backward()

        # Update the parameters
        optimizer.step()

        running_loss += loss.item()

    print(f'Epoch {epoch}/{epochs}, Loss: {running_loss/len(train_loader):.4f}')

# --- 5. Evaluation Loop ---
model.eval() # Set the model to evaluation mode
test_loss = 0
correct = 0
with torch.no_grad(): # Disable gradient calculations during evaluation
    for data, target in test_loader:
        output = model(data)
        test_loss += criterion(output, target).item()  # Sum up batch loss
        pred = output.argmax(dim=1, keepdim=True)  # Get the index of the max log-probability
        correct += pred.eq(target.view_as(pred)).sum().item()

test_loss /= len(test_loader.dataset) / 1000 # Correct average loss calculation

print("-" * 35)
print(f"Test Set Results:")
print(f"Average Loss: {test_loss:.4f}")
print(f"Accuracy: {correct}/{len(test_loader.dataset)} ({100. * correct / len(test_loader.dataset):.2f}%)")

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████████████████████████████████████████████████████████████| 9912422/9912422 [00:00<00:00, 10214828.67it/s]


Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|████████████████████████████████████████████████████████████████████████| 28881/28881 [00:00<00:00, 271850.95it/s]


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|███████████████████████████████████████████████████████████████████| 1648877/1648877 [00:00<00:00, 2677371.44it/s]


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw

Failed to download (trying next):
HTTP Error 404: Not Found



100%|██████████████████████████████████████████████████████████████████████████| 4542/4542 [00:00<00:00, 998769.46it/s]


Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw

Starting PyTorch CNN Training...
Epoch 1/5, Loss: 0.1287
Epoch 2/5, Loss: 0.0426
Epoch 3/5, Loss: 0.0297
Epoch 4/5, Loss: 0.0224
Epoch 5/5, Loss: 0.0173
-----------------------------------
Test Set Results:
Average Loss: 0.0296
Accuracy: 9905/10000 (99.05%)


Key PyTorch Components
torch.nn.Module: All PyTorch models inherit from this base class. The constructor (__init__) defines the layers, and the forward method defines how data flows through the network.

nn.Conv2d: The convolutional layer. It expects input in the shape (Batch_Size, Channels, Height, Width).

nn.MaxPool2d: The pooling layer for downsampling features.

nn.Linear: A standard fully connected (dense) layer.

F.relu: The ReLU activation function from the functional API (torch.nn.functional).

x.view(-1, ...): This is the PyTorch equivalent of Flattening. It reshapes the 4D tensor (from Conv/Pool) into a 2D tensor (Batch_Size, Feature_Vector_Length) where -1 automatically infers the batch size.

torch.no_grad(): Used during evaluation to save memory and computations by ensuring no gradients are calculated, as they aren't needed for prediction.